/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.records;


import com.school.cbis.domain.tables.AutonomousPracticeTemplate;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutonomousPracticeTemplateRecord extends UpdatableRecordImpl<AutonomousPracticeTemplateRecord> implements Record5<Integer, String, Timestamp, String, Integer> {

	private static final long serialVersionUID = -470168824;

	/**
	 * Setter for <code>cbis.autonomous_practice_template.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbis.autonomous_practice_template.id</code>.
	 */
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>cbis.autonomous_practice_template.autonomous_practice_template_title</code>.
	 */
	public void setAutonomousPracticeTemplateTitle(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbis.autonomous_practice_template.autonomous_practice_template_title</code>.
	 */
	@NotNull
	@Size(max = 50)
	public String getAutonomousPracticeTemplateTitle() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>cbis.autonomous_practice_template.create_time</code>.
	 */
	public void setCreateTime(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbis.autonomous_practice_template.create_time</code>.
	 */
	@NotNull
	public Timestamp getCreateTime() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>cbis.autonomous_practice_template.users_id</code>.
	 */
	public void setUsersId(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cbis.autonomous_practice_template.users_id</code>.
	 */
	@NotNull
	@Size(max = 64)
	public String getUsersId() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>cbis.autonomous_practice_template.tie_id</code>.
	 */
	public void setTieId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cbis.autonomous_practice_template.tie_id</code>.
	 */
	@NotNull
	public Integer getTieId() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, Timestamp, String, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, Timestamp, String, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AutonomousPracticeTemplate.AUTONOMOUS_PRACTICE_TEMPLATE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return AutonomousPracticeTemplate.AUTONOMOUS_PRACTICE_TEMPLATE.AUTONOMOUS_PRACTICE_TEMPLATE_TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return AutonomousPracticeTemplate.AUTONOMOUS_PRACTICE_TEMPLATE.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return AutonomousPracticeTemplate.AUTONOMOUS_PRACTICE_TEMPLATE.USERS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return AutonomousPracticeTemplate.AUTONOMOUS_PRACTICE_TEMPLATE.TIE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAutonomousPracticeTemplateTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getUsersId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getTieId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutonomousPracticeTemplateRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutonomousPracticeTemplateRecord value2(String value) {
		setAutonomousPracticeTemplateTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutonomousPracticeTemplateRecord value3(Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutonomousPracticeTemplateRecord value4(String value) {
		setUsersId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutonomousPracticeTemplateRecord value5(Integer value) {
		setTieId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AutonomousPracticeTemplateRecord values(Integer value1, String value2, Timestamp value3, String value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AutonomousPracticeTemplateRecord
	 */
	public AutonomousPracticeTemplateRecord() {
		super(AutonomousPracticeTemplate.AUTONOMOUS_PRACTICE_TEMPLATE);
	}

	/**
	 * Create a detached, initialised AutonomousPracticeTemplateRecord
	 */
	public AutonomousPracticeTemplateRecord(Integer id, String autonomousPracticeTemplateTitle, Timestamp createTime, String usersId, Integer tieId) {
		super(AutonomousPracticeTemplate.AUTONOMOUS_PRACTICE_TEMPLATE);

		setValue(0, id);
		setValue(1, autonomousPracticeTemplateTitle);
		setValue(2, createTime);
		setValue(3, usersId);
		setValue(4, tieId);
	}
}
