/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.records;


import com.school.cbis.domain.tables.BringIn;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BringInRecord extends UpdatableRecordImpl<BringInRecord> implements Record3<Integer, String, String> {

	private static final long serialVersionUID = 1883730843;

	/**
	 * Setter for <code>cbis.bring_in.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbis.bring_in.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>cbis.bring_in.release_article</code>.
	 */
	public void setReleaseArticle(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbis.bring_in.release_article</code>.
	 */
	public String getReleaseArticle() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>cbis.bring_in.HR_email</code>.
	 */
	public void setHrEmail(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbis.bring_in.HR_email</code>.
	 */
	public String getHrEmail() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return BringIn.BRING_IN.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return BringIn.BRING_IN.RELEASE_ARTICLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return BringIn.BRING_IN.HR_EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getReleaseArticle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getHrEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BringInRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BringInRecord value2(String value) {
		setReleaseArticle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BringInRecord value3(String value) {
		setHrEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BringInRecord values(Integer value1, String value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BringInRecord
	 */
	public BringInRecord() {
		super(BringIn.BRING_IN);
	}

	/**
	 * Create a detached, initialised BringInRecord
	 */
	public BringInRecord(Integer id, String releaseArticle, String hrEmail) {
		super(BringIn.BRING_IN);

		setValue(0, id);
		setValue(1, releaseArticle);
		setValue(2, hrEmail);
	}
}
