/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.records;


import com.school.cbis.domain.tables.Recruit;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecruitRecord extends UpdatableRecordImpl<RecruitRecord> implements Record10<Integer, Timestamp, String, String, String, String, String, Integer, String, Timestamp> {

	private static final long serialVersionUID = -1770639465;

	/**
	 * Setter for <code>cbis.recruit.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbis.recruit.id</code>.
	 */
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>cbis.recruit.recruit_time</code>. 招聘时间
	 */
	public void setRecruitTime(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbis.recruit.recruit_time</code>. 招聘时间
	 */
	@NotNull
	public Timestamp getRecruitTime() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>cbis.recruit.recruit_address</code>. 招聘地点
	 */
	public void setRecruitAddress(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbis.recruit.recruit_address</code>. 招聘地点
	 */
	@Size(max = 500)
	public String getRecruitAddress() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>cbis.recruit.recruit_content</code>. 招聘内容
	 */
	public void setRecruitContent(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cbis.recruit.recruit_content</code>. 招聘内容
	 */
	@Size(max = 65535)
	public String getRecruitContent() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>cbis.recruit.text_link</code>. 原文链接
	 */
	public void setTextLink(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cbis.recruit.text_link</code>. 原文链接
	 */
	@Size(max = 1000)
	public String getTextLink() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>cbis.recruit.recruit_title</code>. 招聘标题
	 */
	public void setRecruitTitle(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>cbis.recruit.recruit_title</code>. 招聘标题
	 */
	@Size(max = 100)
	public String getRecruitTitle() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>cbis.recruit.fit_major</code>. 适合专业
	 */
	public void setFitMajor(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>cbis.recruit.fit_major</code>. 适合专业
	 */
	@Size(max = 500)
	public String getFitMajor() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>cbis.recruit.tie_id</code>.
	 */
	public void setTieId(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>cbis.recruit.tie_id</code>.
	 */
	@NotNull
	public Integer getTieId() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>cbis.recruit.username</code>.
	 */
	public void setUsername(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>cbis.recruit.username</code>.
	 */
	@NotNull
	@Size(max = 64)
	public String getUsername() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>cbis.recruit.create_time</code>.
	 */
	public void setCreateTime(Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>cbis.recruit.create_time</code>.
	 */
	@NotNull
	public Timestamp getCreateTime() {
		return (Timestamp) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Timestamp, String, String, String, String, String, Integer, String, Timestamp> fieldsRow() {
		return (Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Timestamp, String, String, String, String, String, Integer, String, Timestamp> valuesRow() {
		return (Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Recruit.RECRUIT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return Recruit.RECRUIT.RECRUIT_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Recruit.RECRUIT.RECRUIT_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Recruit.RECRUIT.RECRUIT_CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Recruit.RECRUIT.TEXT_LINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Recruit.RECRUIT.RECRUIT_TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Recruit.RECRUIT.FIT_MAJOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Recruit.RECRUIT.TIE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Recruit.RECRUIT.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return Recruit.RECRUIT.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getRecruitTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getRecruitAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getRecruitContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getTextLink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getRecruitTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getFitMajor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getTieId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitRecord value2(Timestamp value) {
		setRecruitTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitRecord value3(String value) {
		setRecruitAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitRecord value4(String value) {
		setRecruitContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitRecord value5(String value) {
		setTextLink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitRecord value6(String value) {
		setRecruitTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitRecord value7(String value) {
		setFitMajor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitRecord value8(Integer value) {
		setTieId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitRecord value9(String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitRecord value10(Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitRecord values(Integer value1, Timestamp value2, String value3, String value4, String value5, String value6, String value7, Integer value8, String value9, Timestamp value10) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RecruitRecord
	 */
	public RecruitRecord() {
		super(Recruit.RECRUIT);
	}

	/**
	 * Create a detached, initialised RecruitRecord
	 */
	public RecruitRecord(Integer id, Timestamp recruitTime, String recruitAddress, String recruitContent, String textLink, String recruitTitle, String fitMajor, Integer tieId, String username, Timestamp createTime) {
		super(Recruit.RECRUIT);

		setValue(0, id);
		setValue(1, recruitTime);
		setValue(2, recruitAddress);
		setValue(3, recruitContent);
		setValue(4, textLink);
		setValue(5, recruitTitle);
		setValue(6, fitMajor);
		setValue(7, tieId);
		setValue(8, username);
		setValue(9, createTime);
	}
}
