/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.records;


import com.school.cbis.domain.tables.StudentPoor;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentPoorRecord extends UpdatableRecordImpl<StudentPoorRecord> implements Record4<Integer, String, String, Integer> {

	private static final long serialVersionUID = 771197652;

	/**
	 * Setter for <code>cbis.student_poor.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbis.student_poor.id</code>.
	 */
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>cbis.student_poor.title</code>. 是每年系统自动生成一条记录?(如:2015-2016学年贫困程度)
	 */
	public void setTitle(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbis.student_poor.title</code>. 是每年系统自动生成一条记录?(如:2015-2016学年贫困程度)
	 */
	@Size(max = 200)
	public String getTitle() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>cbis.student_poor.content</code>.
	 */
	public void setContent(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbis.student_poor.content</code>.
	 */
	@Size(max = 100)
	public String getContent() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>cbis.student_poor.student_id</code>.
	 */
	public void setStudentId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cbis.student_poor.student_id</code>.
	 */
	@NotNull
	public Integer getStudentId() {
		return (Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, String, Integer> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, String, Integer> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return StudentPoor.STUDENT_POOR.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return StudentPoor.STUDENT_POOR.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return StudentPoor.STUDENT_POOR.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return StudentPoor.STUDENT_POOR.STUDENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getStudentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentPoorRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentPoorRecord value2(String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentPoorRecord value3(String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentPoorRecord value4(Integer value) {
		setStudentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentPoorRecord values(Integer value1, String value2, String value3, Integer value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StudentPoorRecord
	 */
	public StudentPoorRecord() {
		super(StudentPoor.STUDENT_POOR);
	}

	/**
	 * Create a detached, initialised StudentPoorRecord
	 */
	public StudentPoorRecord(Integer id, String title, String content, Integer studentId) {
		super(StudentPoor.STUDENT_POOR);

		setValue(0, id);
		setValue(1, title);
		setValue(2, content);
		setValue(3, studentId);
	}
}
