/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.records;


import com.school.cbis.domain.tables.SystemLog;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemLogRecord extends UpdatableRecordImpl<SystemLogRecord> implements Record5<Integer, String, String, Timestamp, Integer> {

	private static final long serialVersionUID = 973336139;

	/**
	 * Setter for <code>cbis.system_log.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbis.system_log.id</code>.
	 */
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>cbis.system_log.username</code>. 操作人
	 */
	public void setUsername(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbis.system_log.username</code>. 操作人
	 */
	@NotNull
	@Size(max = 64)
	public String getUsername() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>cbis.system_log.operation_behavior</code>. 操作行为
	 */
	public void setOperationBehavior(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbis.system_log.operation_behavior</code>. 操作行为
	 */
	@Size(max = 200)
	public String getOperationBehavior() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>cbis.system_log.create_time</code>.
	 */
	public void setCreateTime(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cbis.system_log.create_time</code>.
	 */
	@NotNull
	public Timestamp getCreateTime() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>cbis.system_log.tie_id</code>.
	 */
	public void setTieId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cbis.system_log.tie_id</code>.
	 */
	@NotNull
	public Integer getTieId() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, String, Timestamp, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, String, Timestamp, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return SystemLog.SYSTEM_LOG.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return SystemLog.SYSTEM_LOG.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return SystemLog.SYSTEM_LOG.OPERATION_BEHAVIOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return SystemLog.SYSTEM_LOG.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return SystemLog.SYSTEM_LOG.TIE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getOperationBehavior();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getTieId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SystemLogRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SystemLogRecord value2(String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SystemLogRecord value3(String value) {
		setOperationBehavior(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SystemLogRecord value4(Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SystemLogRecord value5(Integer value) {
		setTieId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SystemLogRecord values(Integer value1, String value2, String value3, Timestamp value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SystemLogRecord
	 */
	public SystemLogRecord() {
		super(SystemLog.SYSTEM_LOG);
	}

	/**
	 * Create a detached, initialised SystemLogRecord
	 */
	public SystemLogRecord(Integer id, String username, String operationBehavior, Timestamp createTime, Integer tieId) {
		super(SystemLog.SYSTEM_LOG);

		setValue(0, id);
		setValue(1, username);
		setValue(2, operationBehavior);
		setValue(3, createTime);
		setValue(4, tieId);
	}
}
