/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.records;


import com.school.cbis.domain.tables.TeachTaskContent;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeachTaskContentRecord extends UpdatableRecordImpl<TeachTaskContentRecord> implements Record5<Integer, Integer, String, Integer, Integer> {

	private static final long serialVersionUID = 1477415595;

	/**
	 * Setter for <code>cbis.teach_task_content.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbis.teach_task_content.id</code>.
	 */
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>cbis.teach_task_content.teach_task_title_id</code>.
	 */
	public void setTeachTaskTitleId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbis.teach_task_content.teach_task_title_id</code>.
	 */
	@NotNull
	public Integer getTeachTaskTitleId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>cbis.teach_task_content.content</code>.
	 */
	public void setContent(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbis.teach_task_content.content</code>.
	 */
	@Size(max = 600)
	public String getContent() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>cbis.teach_task_content.content_x</code>.
	 */
	public void setContentX(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cbis.teach_task_content.content_x</code>.
	 */
	@NotNull
	public Integer getContentX() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>cbis.teach_task_content.content_y</code>.
	 */
	public void setContentY(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cbis.teach_task_content.content_y</code>.
	 */
	@NotNull
	public Integer getContentY() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, Integer, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, Integer, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TeachTaskContent.TEACH_TASK_CONTENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return TeachTaskContent.TEACH_TASK_CONTENT.TEACH_TASK_TITLE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TeachTaskContent.TEACH_TASK_CONTENT.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return TeachTaskContent.TEACH_TASK_CONTENT.CONTENT_X;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return TeachTaskContent.TEACH_TASK_CONTENT.CONTENT_Y;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getTeachTaskTitleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getContentX();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getContentY();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachTaskContentRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachTaskContentRecord value2(Integer value) {
		setTeachTaskTitleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachTaskContentRecord value3(String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachTaskContentRecord value4(Integer value) {
		setContentX(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachTaskContentRecord value5(Integer value) {
		setContentY(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachTaskContentRecord values(Integer value1, Integer value2, String value3, Integer value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TeachTaskContentRecord
	 */
	public TeachTaskContentRecord() {
		super(TeachTaskContent.TEACH_TASK_CONTENT);
	}

	/**
	 * Create a detached, initialised TeachTaskContentRecord
	 */
	public TeachTaskContentRecord(Integer id, Integer teachTaskTitleId, String content, Integer contentX, Integer contentY) {
		super(TeachTaskContent.TEACH_TASK_CONTENT);

		setValue(0, id);
		setValue(1, teachTaskTitleId);
		setValue(2, content);
		setValue(3, contentX);
		setValue(4, contentY);
	}
}
