/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.records;


import com.school.cbis.domain.tables.TeachingMaterialContent;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeachingMaterialContentRecord extends UpdatableRecordImpl<TeachingMaterialContentRecord> implements Record5<Integer, String, Integer, Integer, Integer> {

	private static final long serialVersionUID = -1554509856;

	/**
	 * Setter for <code>cbis.teaching_material_content.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbis.teaching_material_content.id</code>.
	 */
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>cbis.teaching_material_content.content</code>.
	 */
	public void setContent(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbis.teaching_material_content.content</code>.
	 */
	@Size(max = 500)
	public String getContent() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>cbis.teaching_material_content.teaching_material_head_id</code>.
	 */
	public void setTeachingMaterialHeadId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbis.teaching_material_content.teaching_material_head_id</code>.
	 */
	@NotNull
	public Integer getTeachingMaterialHeadId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>cbis.teaching_material_content.teacher_id</code>.
	 */
	public void setTeacherId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cbis.teaching_material_content.teacher_id</code>.
	 */
	public Integer getTeacherId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>cbis.teaching_material_content.content_x</code>.
	 */
	public void setContentX(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cbis.teaching_material_content.content_x</code>.
	 */
	@NotNull
	public Integer getContentX() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, Integer, Integer, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, Integer, Integer, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TeachingMaterialContent.TEACHING_MATERIAL_CONTENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TeachingMaterialContent.TEACHING_MATERIAL_CONTENT.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return TeachingMaterialContent.TEACHING_MATERIAL_CONTENT.TEACHING_MATERIAL_HEAD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return TeachingMaterialContent.TEACHING_MATERIAL_CONTENT.TEACHER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return TeachingMaterialContent.TEACHING_MATERIAL_CONTENT.CONTENT_X;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getTeachingMaterialHeadId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getTeacherId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getContentX();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachingMaterialContentRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachingMaterialContentRecord value2(String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachingMaterialContentRecord value3(Integer value) {
		setTeachingMaterialHeadId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachingMaterialContentRecord value4(Integer value) {
		setTeacherId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachingMaterialContentRecord value5(Integer value) {
		setContentX(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachingMaterialContentRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TeachingMaterialContentRecord
	 */
	public TeachingMaterialContentRecord() {
		super(TeachingMaterialContent.TEACHING_MATERIAL_CONTENT);
	}

	/**
	 * Create a detached, initialised TeachingMaterialContentRecord
	 */
	public TeachingMaterialContentRecord(Integer id, String content, Integer teachingMaterialHeadId, Integer teacherId, Integer contentX) {
		super(TeachingMaterialContent.TEACHING_MATERIAL_CONTENT);

		setValue(0, id);
		setValue(1, content);
		setValue(2, teachingMaterialHeadId);
		setValue(3, teacherId);
		setValue(4, contentX);
	}
}
