/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.records;


import com.school.cbis.domain.tables.TeachingMaterialInfo;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeachingMaterialInfoRecord extends UpdatableRecordImpl<TeachingMaterialInfoRecord> implements Record8<Integer, String, Timestamp, Integer, Timestamp, Timestamp, String, Integer> {

	private static final long serialVersionUID = 1080535348;

	/**
	 * Setter for <code>cbis.teaching_material_info.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbis.teaching_material_info.id</code>.
	 */
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>cbis.teaching_material_info.title</code>.
	 */
	public void setTitle(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbis.teaching_material_info.title</code>.
	 */
	@NotNull
	@Size(max = 100)
	public String getTitle() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>cbis.teaching_material_info.create_time</code>.
	 */
	public void setCreateTime(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbis.teaching_material_info.create_time</code>.
	 */
	@NotNull
	public Timestamp getCreateTime() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>cbis.teaching_material_info.teaching_material_template_id</code>.
	 */
	public void setTeachingMaterialTemplateId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cbis.teaching_material_info.teaching_material_template_id</code>.
	 */
	@NotNull
	public Integer getTeachingMaterialTemplateId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>cbis.teaching_material_info.start_time</code>.
	 */
	public void setStartTime(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cbis.teaching_material_info.start_time</code>.
	 */
	@NotNull
	public Timestamp getStartTime() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>cbis.teaching_material_info.end_time</code>.
	 */
	public void setEndTime(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>cbis.teaching_material_info.end_time</code>.
	 */
	@NotNull
	public Timestamp getEndTime() {
		return (Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>cbis.teaching_material_info.users_id</code>.
	 */
	public void setUsersId(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>cbis.teaching_material_info.users_id</code>.
	 */
	@NotNull
	@Size(max = 64)
	public String getUsersId() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>cbis.teaching_material_info.tie_id</code>.
	 */
	public void setTieId(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>cbis.teaching_material_info.tie_id</code>.
	 */
	@NotNull
	public Integer getTieId() {
		return (Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, String, Timestamp, Integer, Timestamp, Timestamp, String, Integer> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, String, Timestamp, Integer, Timestamp, Timestamp, String, Integer> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TeachingMaterialInfo.TEACHING_MATERIAL_INFO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TeachingMaterialInfo.TEACHING_MATERIAL_INFO.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return TeachingMaterialInfo.TEACHING_MATERIAL_INFO.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return TeachingMaterialInfo.TEACHING_MATERIAL_INFO.TEACHING_MATERIAL_TEMPLATE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return TeachingMaterialInfo.TEACHING_MATERIAL_INFO.START_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return TeachingMaterialInfo.TEACHING_MATERIAL_INFO.END_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return TeachingMaterialInfo.TEACHING_MATERIAL_INFO.USERS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return TeachingMaterialInfo.TEACHING_MATERIAL_INFO.TIE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getTeachingMaterialTemplateId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getStartTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getEndTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getUsersId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getTieId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachingMaterialInfoRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachingMaterialInfoRecord value2(String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachingMaterialInfoRecord value3(Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachingMaterialInfoRecord value4(Integer value) {
		setTeachingMaterialTemplateId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachingMaterialInfoRecord value5(Timestamp value) {
		setStartTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachingMaterialInfoRecord value6(Timestamp value) {
		setEndTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachingMaterialInfoRecord value7(String value) {
		setUsersId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachingMaterialInfoRecord value8(Integer value) {
		setTieId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachingMaterialInfoRecord values(Integer value1, String value2, Timestamp value3, Integer value4, Timestamp value5, Timestamp value6, String value7, Integer value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TeachingMaterialInfoRecord
	 */
	public TeachingMaterialInfoRecord() {
		super(TeachingMaterialInfo.TEACHING_MATERIAL_INFO);
	}

	/**
	 * Create a detached, initialised TeachingMaterialInfoRecord
	 */
	public TeachingMaterialInfoRecord(Integer id, String title, Timestamp createTime, Integer teachingMaterialTemplateId, Timestamp startTime, Timestamp endTime, String usersId, Integer tieId) {
		super(TeachingMaterialInfo.TEACHING_MATERIAL_INFO);

		setValue(0, id);
		setValue(1, title);
		setValue(2, createTime);
		setValue(3, teachingMaterialTemplateId);
		setValue(4, startTime);
		setValue(5, endTime);
		setValue(6, usersId);
		setValue(7, tieId);
	}
}
