/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.records;


import com.school.cbis.domain.tables.TeacherFillTaskContent;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherFillTaskContentRecord extends UpdatableRecordImpl<TeacherFillTaskContentRecord> implements Record5<Integer, String, Integer, Integer, Integer> {

	private static final long serialVersionUID = -1605675242;

	/**
	 * Setter for <code>cbis.teacher_fill_task_content.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbis.teacher_fill_task_content.id</code>.
	 */
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>cbis.teacher_fill_task_content.content</code>.
	 */
	public void setContent(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbis.teacher_fill_task_content.content</code>.
	 */
	@Size(max = 500)
	public String getContent() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>cbis.teacher_fill_task_content.teacher_fill_task_head_id</code>.
	 */
	public void setTeacherFillTaskHeadId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbis.teacher_fill_task_content.teacher_fill_task_head_id</code>.
	 */
	@NotNull
	public Integer getTeacherFillTaskHeadId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>cbis.teacher_fill_task_content.teacher_id</code>.
	 */
	public void setTeacherId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cbis.teacher_fill_task_content.teacher_id</code>.
	 */
	@NotNull
	public Integer getTeacherId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>cbis.teacher_fill_task_content.teacher_fill_task_info_id</code>.
	 */
	public void setTeacherFillTaskInfoId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cbis.teacher_fill_task_content.teacher_fill_task_info_id</code>.
	 */
	@NotNull
	public Integer getTeacherFillTaskInfoId() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, Integer, Integer, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, Integer, Integer, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TeacherFillTaskContent.TEACHER_FILL_TASK_CONTENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TeacherFillTaskContent.TEACHER_FILL_TASK_CONTENT.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return TeacherFillTaskContent.TEACHER_FILL_TASK_CONTENT.TEACHER_FILL_TASK_HEAD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return TeacherFillTaskContent.TEACHER_FILL_TASK_CONTENT.TEACHER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return TeacherFillTaskContent.TEACHER_FILL_TASK_CONTENT.TEACHER_FILL_TASK_INFO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getTeacherFillTaskHeadId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getTeacherId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getTeacherFillTaskInfoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherFillTaskContentRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherFillTaskContentRecord value2(String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherFillTaskContentRecord value3(Integer value) {
		setTeacherFillTaskHeadId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherFillTaskContentRecord value4(Integer value) {
		setTeacherId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherFillTaskContentRecord value5(Integer value) {
		setTeacherFillTaskInfoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherFillTaskContentRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TeacherFillTaskContentRecord
	 */
	public TeacherFillTaskContentRecord() {
		super(TeacherFillTaskContent.TEACHER_FILL_TASK_CONTENT);
	}

	/**
	 * Create a detached, initialised TeacherFillTaskContentRecord
	 */
	public TeacherFillTaskContentRecord(Integer id, String content, Integer teacherFillTaskHeadId, Integer teacherId, Integer teacherFillTaskInfoId) {
		super(TeacherFillTaskContent.TEACHER_FILL_TASK_CONTENT);

		setValue(0, id);
		setValue(1, content);
		setValue(2, teacherFillTaskHeadId);
		setValue(3, teacherId);
		setValue(4, teacherFillTaskInfoId);
	}
}
