/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.records;


import com.school.cbis.domain.tables.Teacher;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherRecord extends UpdatableRecordImpl<TeacherRecord> implements Record12<Integer, Integer, String, String, String, String, Date, String, String, String, String, String> {

	private static final long serialVersionUID = 1197201975;

	/**
	 * Setter for <code>cbis.teacher.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbis.teacher.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>cbis.teacher.tie_id</code>.
	 */
	public void setTieId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbis.teacher.tie_id</code>.
	 */
	public Integer getTieId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>cbis.teacher.teacher_job_number</code>.
	 */
	public void setTeacherJobNumber(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbis.teacher.teacher_job_number</code>.
	 */
	public String getTeacherJobNumber() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>cbis.teacher.teacher_name</code>.
	 */
	public void setTeacherName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cbis.teacher.teacher_name</code>.
	 */
	public String getTeacherName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>cbis.teacher.teacher_phone</code>.
	 */
	public void setTeacherPhone(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cbis.teacher.teacher_phone</code>.
	 */
	public String getTeacherPhone() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>cbis.teacher.teacher_email</code>.
	 */
	public void setTeacherEmail(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>cbis.teacher.teacher_email</code>.
	 */
	public String getTeacherEmail() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>cbis.teacher.teacher_birthday</code>.
	 */
	public void setTeacherBirthday(Date value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>cbis.teacher.teacher_birthday</code>.
	 */
	public Date getTeacherBirthday() {
		return (Date) getValue(6);
	}

	/**
	 * Setter for <code>cbis.teacher.teacher_head_photo</code>.
	 */
	public void setTeacherHeadPhoto(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>cbis.teacher.teacher_head_photo</code>.
	 */
	public String getTeacherHeadPhoto() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>cbis.teacher.teacher_sex</code>.
	 */
	public void setTeacherSex(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>cbis.teacher.teacher_sex</code>.
	 */
	public String getTeacherSex() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>cbis.teacher.teacher_introduce</code>.
	 */
	public void setTeacherIntroduce(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>cbis.teacher.teacher_introduce</code>.
	 */
	public String getTeacherIntroduce() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>cbis.teacher.teacher_identity_card</code>.
	 */
	public void setTeacherIdentityCard(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>cbis.teacher.teacher_identity_card</code>.
	 */
	public String getTeacherIdentityCard() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>cbis.teacher.teacher_address</code>.
	 */
	public void setTeacherAddress(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>cbis.teacher.teacher_address</code>.
	 */
	public String getTeacherAddress() {
		return (String) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<Integer, Integer, String, String, String, String, Date, String, String, String, String, String> fieldsRow() {
		return (Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<Integer, Integer, String, String, String, String, Date, String, String, String, String, String> valuesRow() {
		return (Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Teacher.TEACHER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Teacher.TEACHER.TIE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Teacher.TEACHER.TEACHER_JOB_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Teacher.TEACHER.TEACHER_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Teacher.TEACHER.TEACHER_PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Teacher.TEACHER.TEACHER_EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field7() {
		return Teacher.TEACHER.TEACHER_BIRTHDAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Teacher.TEACHER.TEACHER_HEAD_PHOTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Teacher.TEACHER.TEACHER_SEX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return Teacher.TEACHER.TEACHER_INTRODUCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return Teacher.TEACHER.TEACHER_IDENTITY_CARD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return Teacher.TEACHER.TEACHER_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getTieId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getTeacherJobNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getTeacherName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getTeacherPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getTeacherEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value7() {
		return getTeacherBirthday();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getTeacherHeadPhoto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getTeacherSex();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getTeacherIntroduce();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getTeacherIdentityCard();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getTeacherAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherRecord value2(Integer value) {
		setTieId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherRecord value3(String value) {
		setTeacherJobNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherRecord value4(String value) {
		setTeacherName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherRecord value5(String value) {
		setTeacherPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherRecord value6(String value) {
		setTeacherEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherRecord value7(Date value) {
		setTeacherBirthday(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherRecord value8(String value) {
		setTeacherHeadPhoto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherRecord value9(String value) {
		setTeacherSex(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherRecord value10(String value) {
		setTeacherIntroduce(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherRecord value11(String value) {
		setTeacherIdentityCard(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherRecord value12(String value) {
		setTeacherAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherRecord values(Integer value1, Integer value2, String value3, String value4, String value5, String value6, Date value7, String value8, String value9, String value10, String value11, String value12) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TeacherRecord
	 */
	public TeacherRecord() {
		super(Teacher.TEACHER);
	}

	/**
	 * Create a detached, initialised TeacherRecord
	 */
	public TeacherRecord(Integer id, Integer tieId, String teacherJobNumber, String teacherName, String teacherPhone, String teacherEmail, Date teacherBirthday, String teacherHeadPhoto, String teacherSex, String teacherIntroduce, String teacherIdentityCard, String teacherAddress) {
		super(Teacher.TEACHER);

		setValue(0, id);
		setValue(1, tieId);
		setValue(2, teacherJobNumber);
		setValue(3, teacherName);
		setValue(4, teacherPhone);
		setValue(5, teacherEmail);
		setValue(6, teacherBirthday);
		setValue(7, teacherHeadPhoto);
		setValue(8, teacherSex);
		setValue(9, teacherIntroduce);
		setValue(10, teacherIdentityCard);
		setValue(11, teacherAddress);
	}
}
