/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.records;


import com.school.cbis.domain.tables.TieElegant;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TieElegantRecord extends UpdatableRecordImpl<TieElegantRecord> implements Record4<Integer, Integer, Integer, Integer> {

	private static final long serialVersionUID = -368906907;

	/**
	 * Setter for <code>cbis.tie_elegant.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cbis.tie_elegant.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>cbis.tie_elegant.tie_id</code>.
	 */
	public void setTieId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cbis.tie_elegant.tie_id</code>.
	 */
	public Integer getTieId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>cbis.tie_elegant.tie_elegant_article_info_id</code>.
	 */
	public void setTieElegantArticleInfoId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cbis.tie_elegant.tie_elegant_article_info_id</code>.
	 */
	public Integer getTieElegantArticleInfoId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>cbis.tie_elegant.tie_elegant_time_id</code>.
	 */
	public void setTieElegantTimeId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cbis.tie_elegant.tie_elegant_time_id</code>.
	 */
	public Integer getTieElegantTimeId() {
		return (Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, Integer, Integer> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TieElegant.TIE_ELEGANT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return TieElegant.TIE_ELEGANT.TIE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return TieElegant.TIE_ELEGANT.TIE_ELEGANT_ARTICLE_INFO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return TieElegant.TIE_ELEGANT.TIE_ELEGANT_TIME_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getTieId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getTieElegantArticleInfoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getTieElegantTimeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TieElegantRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TieElegantRecord value2(Integer value) {
		setTieId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TieElegantRecord value3(Integer value) {
		setTieElegantArticleInfoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TieElegantRecord value4(Integer value) {
		setTieElegantTimeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TieElegantRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TieElegantRecord
	 */
	public TieElegantRecord() {
		super(TieElegant.TIE_ELEGANT);
	}

	/**
	 * Create a detached, initialised TieElegantRecord
	 */
	public TieElegantRecord(Integer id, Integer tieId, Integer tieElegantArticleInfoId, Integer tieElegantTimeId) {
		super(TieElegant.TIE_ELEGANT);

		setValue(0, id);
		setValue(1, tieId);
		setValue(2, tieElegantArticleInfoId);
		setValue(3, tieElegantTimeId);
	}
}
