/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.daos;


import com.school.cbis.domain.tables.ArticleType;
import com.school.cbis.domain.tables.records.ArticleTypeRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleTypeDao extends DAOImpl<ArticleTypeRecord, com.school.cbis.domain.tables.pojos.ArticleType, Integer> {

	/**
	 * Create a new ArticleTypeDao without any configuration
	 */
	public ArticleTypeDao() {
		super(ArticleType.ARTICLE_TYPE, com.school.cbis.domain.tables.pojos.ArticleType.class);
	}

	/**
	 * Create a new ArticleTypeDao with an attached configuration
	 */
	public ArticleTypeDao(Configuration configuration) {
		super(ArticleType.ARTICLE_TYPE, com.school.cbis.domain.tables.pojos.ArticleType.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(com.school.cbis.domain.tables.pojos.ArticleType object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.ArticleType> fetchById(Integer... values) {
		return fetch(ArticleType.ARTICLE_TYPE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.school.cbis.domain.tables.pojos.ArticleType fetchOneById(Integer value) {
		return fetchOne(ArticleType.ARTICLE_TYPE.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.ArticleType> fetchByName(String... values) {
		return fetch(ArticleType.ARTICLE_TYPE.NAME, values);
	}
}
