/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.daos;


import com.school.cbis.domain.tables.ArticleSub;
import com.school.cbis.domain.tables.records.ArticleSubRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleSubDao extends DAOImpl<ArticleSubRecord, com.school.cbis.domain.tables.pojos.ArticleSub, Integer> {

	/**
	 * Create a new ArticleSubDao without any configuration
	 */
	public ArticleSubDao() {
		super(ArticleSub.ARTICLE_SUB, com.school.cbis.domain.tables.pojos.ArticleSub.class);
	}

	/**
	 * Create a new ArticleSubDao with an attached configuration
	 */
	public ArticleSubDao(Configuration configuration) {
		super(ArticleSub.ARTICLE_SUB, com.school.cbis.domain.tables.pojos.ArticleSub.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(com.school.cbis.domain.tables.pojos.ArticleSub object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.ArticleSub> fetchById(Integer... values) {
		return fetch(ArticleSub.ARTICLE_SUB.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.school.cbis.domain.tables.pojos.ArticleSub fetchOneById(Integer value) {
		return fetchOne(ArticleSub.ARTICLE_SUB.ID, value);
	}

	/**
	 * Fetch records that have <code>sub_title IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.ArticleSub> fetchBySubTitle(String... values) {
		return fetch(ArticleSub.ARTICLE_SUB.SUB_TITLE, values);
	}

	/**
	 * Fetch records that have <code>sub_content IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.ArticleSub> fetchBySubContent(String... values) {
		return fetch(ArticleSub.ARTICLE_SUB.SUB_CONTENT, values);
	}

	/**
	 * Fetch records that have <code>article_info_id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.ArticleSub> fetchByArticleInfoId(Integer... values) {
		return fetch(ArticleSub.ARTICLE_SUB.ARTICLE_INFO_ID, values);
	}
}
