/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.daos;


import com.school.cbis.domain.tables.Grade;
import com.school.cbis.domain.tables.records.GradeRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GradeDao extends DAOImpl<GradeRecord, com.school.cbis.domain.tables.pojos.Grade, Integer> {

	/**
	 * Create a new GradeDao without any configuration
	 */
	public GradeDao() {
		super(Grade.GRADE, com.school.cbis.domain.tables.pojos.Grade.class);
	}

	/**
	 * Create a new GradeDao with an attached configuration
	 */
	public GradeDao(Configuration configuration) {
		super(Grade.GRADE, com.school.cbis.domain.tables.pojos.Grade.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(com.school.cbis.domain.tables.pojos.Grade object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.Grade> fetchById(Integer... values) {
		return fetch(Grade.GRADE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.school.cbis.domain.tables.pojos.Grade fetchOneById(Integer value) {
		return fetchOne(Grade.GRADE.ID, value);
	}

	/**
	 * Fetch records that have <code>major_id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.Grade> fetchByMajorId(Integer... values) {
		return fetch(Grade.GRADE.MAJOR_ID, values);
	}

	/**
	 * Fetch records that have <code>year IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.Grade> fetchByYear(String... values) {
		return fetch(Grade.GRADE.YEAR, values);
	}

	/**
	 * Fetch records that have <code>grade_name IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.Grade> fetchByGradeName(String... values) {
		return fetch(Grade.GRADE.GRADE_NAME, values);
	}

	/**
	 * Fetch records that have <code>grade_head IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.Grade> fetchByGradeHead(String... values) {
		return fetch(Grade.GRADE.GRADE_HEAD, values);
	}
}
