/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.daos;


import com.school.cbis.domain.tables.PlaceFileInfo;
import com.school.cbis.domain.tables.records.PlaceFileInfoRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlaceFileInfoDao extends DAOImpl<PlaceFileInfoRecord, com.school.cbis.domain.tables.pojos.PlaceFileInfo, Integer> {

	/**
	 * Create a new PlaceFileInfoDao without any configuration
	 */
	public PlaceFileInfoDao() {
		super(PlaceFileInfo.PLACE_FILE_INFO, com.school.cbis.domain.tables.pojos.PlaceFileInfo.class);
	}

	/**
	 * Create a new PlaceFileInfoDao with an attached configuration
	 */
	public PlaceFileInfoDao(Configuration configuration) {
		super(PlaceFileInfo.PLACE_FILE_INFO, com.school.cbis.domain.tables.pojos.PlaceFileInfo.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(com.school.cbis.domain.tables.pojos.PlaceFileInfo object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.PlaceFileInfo> fetchById(Integer... values) {
		return fetch(PlaceFileInfo.PLACE_FILE_INFO.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.school.cbis.domain.tables.pojos.PlaceFileInfo fetchOneById(Integer value) {
		return fetchOne(PlaceFileInfo.PLACE_FILE_INFO.ID, value);
	}

	/**
	 * Fetch records that have <code>teach_task_info_id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.PlaceFileInfo> fetchByTeachTaskInfoId(Integer... values) {
		return fetch(PlaceFileInfo.PLACE_FILE_INFO.TEACH_TASK_INFO_ID, values);
	}

	/**
	 * Fetch records that have <code>place_file_info_url IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.PlaceFileInfo> fetchByPlaceFileInfoUrl(String... values) {
		return fetch(PlaceFileInfo.PLACE_FILE_INFO.PLACE_FILE_INFO_URL, values);
	}

	/**
	 * Fetch records that have <code>place_file_info_size IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.PlaceFileInfo> fetchByPlaceFileInfoSize(String... values) {
		return fetch(PlaceFileInfo.PLACE_FILE_INFO.PLACE_FILE_INFO_SIZE, values);
	}

	/**
	 * Fetch records that have <code>place_file_info_name IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.PlaceFileInfo> fetchByPlaceFileInfoName(String... values) {
		return fetch(PlaceFileInfo.PLACE_FILE_INFO.PLACE_FILE_INFO_NAME, values);
	}

	/**
	 * Fetch records that have <code>place_file_info_date IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.PlaceFileInfo> fetchByPlaceFileInfoDate(Timestamp... values) {
		return fetch(PlaceFileInfo.PLACE_FILE_INFO.PLACE_FILE_INFO_DATE, values);
	}

	/**
	 * Fetch records that have <code>file_user IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.PlaceFileInfo> fetchByFileUser(String... values) {
		return fetch(PlaceFileInfo.PLACE_FILE_INFO.FILE_USER, values);
	}

	/**
	 * Fetch records that have <code>file_type IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.PlaceFileInfo> fetchByFileType(String... values) {
		return fetch(PlaceFileInfo.PLACE_FILE_INFO.FILE_TYPE, values);
	}
}
