/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.daos;


import com.school.cbis.domain.tables.TeacherCourseTimetableInfo;
import com.school.cbis.domain.tables.records.TeacherCourseTimetableInfoRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherCourseTimetableInfoDao extends DAOImpl<TeacherCourseTimetableInfoRecord, com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo, Integer> {

	/**
	 * Create a new TeacherCourseTimetableInfoDao without any configuration
	 */
	public TeacherCourseTimetableInfoDao() {
		super(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO, com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo.class);
	}

	/**
	 * Create a new TeacherCourseTimetableInfoDao with an attached configuration
	 */
	public TeacherCourseTimetableInfoDao(Configuration configuration) {
		super(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO, com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo> fetchById(Integer... values) {
		return fetch(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo fetchOneById(Integer value) {
		return fetchOne(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO.ID, value);
	}

	/**
	 * Fetch records that have <code>tie_id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo> fetchByTieId(Integer... values) {
		return fetch(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO.TIE_ID, values);
	}

	/**
	 * Fetch records that have <code>timetable_info_term IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo> fetchByTimetableInfoTerm(String... values) {
		return fetch(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO.TIMETABLE_INFO_TERM, values);
	}

	/**
	 * Fetch records that have <code>timetable_info_file_url IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo> fetchByTimetableInfoFileUrl(String... values) {
		return fetch(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO.TIMETABLE_INFO_FILE_URL, values);
	}

	/**
	 * Fetch records that have <code>timetable_info_file_pdf IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo> fetchByTimetableInfoFilePdf(String... values) {
		return fetch(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO.TIMETABLE_INFO_FILE_PDF, values);
	}

	/**
	 * Fetch records that have <code>timetable_info_file_size IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo> fetchByTimetableInfoFileSize(String... values) {
		return fetch(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO.TIMETABLE_INFO_FILE_SIZE, values);
	}

	/**
	 * Fetch records that have <code>timetable_info_file_name IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo> fetchByTimetableInfoFileName(String... values) {
		return fetch(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO.TIMETABLE_INFO_FILE_NAME, values);
	}

	/**
	 * Fetch records that have <code>timetable_info_file_date IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo> fetchByTimetableInfoFileDate(Timestamp... values) {
		return fetch(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO.TIMETABLE_INFO_FILE_DATE, values);
	}

	/**
	 * Fetch records that have <code>timetable_info_file_down_times IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo> fetchByTimetableInfoFileDownTimes(Integer... values) {
		return fetch(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO.TIMETABLE_INFO_FILE_DOWN_TIMES, values);
	}

	/**
	 * Fetch records that have <code>teach_type_id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo> fetchByTeachTypeId(Integer... values) {
		return fetch(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO.TEACH_TYPE_ID, values);
	}

	/**
	 * Fetch records that have <code>term_start_time IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo> fetchByTermStartTime(Date... values) {
		return fetch(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO.TERM_START_TIME, values);
	}

	/**
	 * Fetch records that have <code>term_end_time IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo> fetchByTermEndTime(Date... values) {
		return fetch(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO.TERM_END_TIME, values);
	}

	/**
	 * Fetch records that have <code>file_user IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo> fetchByFileUser(String... values) {
		return fetch(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO.FILE_USER, values);
	}

	/**
	 * Fetch records that have <code>file_type IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo> fetchByFileType(String... values) {
		return fetch(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO.FILE_TYPE, values);
	}

	/**
	 * Fetch records that have <code>teacher_id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeacherCourseTimetableInfo> fetchByTeacherId(Integer... values) {
		return fetch(TeacherCourseTimetableInfo.TEACHER_COURSE_TIMETABLE_INFO.TEACHER_ID, values);
	}
}
