/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.daos;


import com.school.cbis.domain.tables.TeachTaskTitle;
import com.school.cbis.domain.tables.records.TeachTaskTitleRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeachTaskTitleDao extends DAOImpl<TeachTaskTitleRecord, com.school.cbis.domain.tables.pojos.TeachTaskTitle, Integer> {

	/**
	 * Create a new TeachTaskTitleDao without any configuration
	 */
	public TeachTaskTitleDao() {
		super(TeachTaskTitle.TEACH_TASK_TITLE, com.school.cbis.domain.tables.pojos.TeachTaskTitle.class);
	}

	/**
	 * Create a new TeachTaskTitleDao with an attached configuration
	 */
	public TeachTaskTitleDao(Configuration configuration) {
		super(TeachTaskTitle.TEACH_TASK_TITLE, com.school.cbis.domain.tables.pojos.TeachTaskTitle.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(com.school.cbis.domain.tables.pojos.TeachTaskTitle object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeachTaskTitle> fetchById(Integer... values) {
		return fetch(TeachTaskTitle.TEACH_TASK_TITLE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.school.cbis.domain.tables.pojos.TeachTaskTitle fetchOneById(Integer value) {
		return fetchOne(TeachTaskTitle.TEACH_TASK_TITLE.ID, value);
	}

	/**
	 * Fetch records that have <code>title IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeachTaskTitle> fetchByTitle(String... values) {
		return fetch(TeachTaskTitle.TEACH_TASK_TITLE.TITLE, values);
	}

	/**
	 * Fetch records that have <code>title_x IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeachTaskTitle> fetchByTitleX(Integer... values) {
		return fetch(TeachTaskTitle.TEACH_TASK_TITLE.TITLE_X, values);
	}

	/**
	 * Fetch records that have <code>title_y IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeachTaskTitle> fetchByTitleY(Integer... values) {
		return fetch(TeachTaskTitle.TEACH_TASK_TITLE.TITLE_Y, values);
	}

	/**
	 * Fetch records that have <code>teach_task_info_id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeachTaskTitle> fetchByTeachTaskInfoId(Integer... values) {
		return fetch(TeachTaskTitle.TEACH_TASK_TITLE.TEACH_TASK_INFO_ID, values);
	}
}
