/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.daos;


import com.school.cbis.domain.tables.TeachingMaterialContent;
import com.school.cbis.domain.tables.records.TeachingMaterialContentRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeachingMaterialContentDao extends DAOImpl<TeachingMaterialContentRecord, com.school.cbis.domain.tables.pojos.TeachingMaterialContent, Integer> {

	/**
	 * Create a new TeachingMaterialContentDao without any configuration
	 */
	public TeachingMaterialContentDao() {
		super(TeachingMaterialContent.TEACHING_MATERIAL_CONTENT, com.school.cbis.domain.tables.pojos.TeachingMaterialContent.class);
	}

	/**
	 * Create a new TeachingMaterialContentDao with an attached configuration
	 */
	public TeachingMaterialContentDao(Configuration configuration) {
		super(TeachingMaterialContent.TEACHING_MATERIAL_CONTENT, com.school.cbis.domain.tables.pojos.TeachingMaterialContent.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(com.school.cbis.domain.tables.pojos.TeachingMaterialContent object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeachingMaterialContent> fetchById(Integer... values) {
		return fetch(TeachingMaterialContent.TEACHING_MATERIAL_CONTENT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.school.cbis.domain.tables.pojos.TeachingMaterialContent fetchOneById(Integer value) {
		return fetchOne(TeachingMaterialContent.TEACHING_MATERIAL_CONTENT.ID, value);
	}

	/**
	 * Fetch records that have <code>content IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeachingMaterialContent> fetchByContent(String... values) {
		return fetch(TeachingMaterialContent.TEACHING_MATERIAL_CONTENT.CONTENT, values);
	}

	/**
	 * Fetch records that have <code>teaching_material_head_id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeachingMaterialContent> fetchByTeachingMaterialHeadId(Integer... values) {
		return fetch(TeachingMaterialContent.TEACHING_MATERIAL_CONTENT.TEACHING_MATERIAL_HEAD_ID, values);
	}

	/**
	 * Fetch records that have <code>teacher_id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeachingMaterialContent> fetchByTeacherId(Integer... values) {
		return fetch(TeachingMaterialContent.TEACHING_MATERIAL_CONTENT.TEACHER_ID, values);
	}

	/**
	 * Fetch records that have <code>content_x IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.TeachingMaterialContent> fetchByContentX(Integer... values) {
		return fetch(TeachingMaterialContent.TEACHING_MATERIAL_CONTENT.CONTENT_X, values);
	}
}
