/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.daos;


import com.school.cbis.domain.tables.Users;
import com.school.cbis.domain.tables.records.UsersRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersDao extends DAOImpl<UsersRecord, com.school.cbis.domain.tables.pojos.Users, String> {

	/**
	 * Create a new UsersDao without any configuration
	 */
	public UsersDao() {
		super(Users.USERS, com.school.cbis.domain.tables.pojos.Users.class);
	}

	/**
	 * Create a new UsersDao with an attached configuration
	 */
	public UsersDao(Configuration configuration) {
		super(Users.USERS, com.school.cbis.domain.tables.pojos.Users.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected String getId(com.school.cbis.domain.tables.pojos.Users object) {
		return object.getUsername();
	}

	/**
	 * Fetch records that have <code>username IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.Users> fetchByUsername(String... values) {
		return fetch(Users.USERS.USERNAME, values);
	}

	/**
	 * Fetch a unique record that has <code>username = value</code>
	 */
	public com.school.cbis.domain.tables.pojos.Users fetchOneByUsername(String value) {
		return fetchOne(Users.USERS.USERNAME, value);
	}

	/**
	 * Fetch records that have <code>password IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.Users> fetchByPassword(String... values) {
		return fetch(Users.USERS.PASSWORD, values);
	}

	/**
	 * Fetch records that have <code>enabled IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.Users> fetchByEnabled(Byte... values) {
		return fetch(Users.USERS.ENABLED, values);
	}

	/**
	 * Fetch records that have <code>user_type_id IN (values)</code>
	 */
	public List<com.school.cbis.domain.tables.pojos.Users> fetchByUserTypeId(Integer... values) {
		return fetch(Users.USERS.USER_TYPE_ID, values);
	}
}
