/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables;


import com.school.cbis.domain.Cbis;
import com.school.cbis.domain.Keys;
import com.school.cbis.domain.tables.records.FourItemsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FourItems extends TableImpl<FourItemsRecord> {

	private static final long serialVersionUID = 924948390;

	/**
	 * The reference instance of <code>cbis.four_items</code>
	 */
	public static final FourItems FOUR_ITEMS = new FourItems();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FourItemsRecord> getRecordType() {
		return FourItemsRecord.class;
	}

	/**
	 * The column <code>cbis.four_items.id</code>.
	 */
	public final TableField<FourItemsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.four_items.teach_task_info_id</code>.
	 */
	public final TableField<FourItemsRecord, Integer> TEACH_TASK_INFO_ID = createField("teach_task_info_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.four_items.content_x</code>.
	 */
	public final TableField<FourItemsRecord, Integer> CONTENT_X = createField("content_x", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.four_items.four_items_file_url</code>.
	 */
	public final TableField<FourItemsRecord, String> FOUR_ITEMS_FILE_URL = createField("four_items_file_url", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false), this, "");

	/**
	 * The column <code>cbis.four_items.four_items_file_size</code>.
	 */
	public final TableField<FourItemsRecord, String> FOUR_ITEMS_FILE_SIZE = createField("four_items_file_size", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>cbis.four_items.four_items_file_name</code>.
	 */
	public final TableField<FourItemsRecord, String> FOUR_ITEMS_FILE_NAME = createField("four_items_file_name", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>cbis.four_items.four_items_file_date</code>.
	 */
	public final TableField<FourItemsRecord, Timestamp> FOUR_ITEMS_FILE_DATE = createField("four_items_file_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>cbis.four_items.file_user</code>.
	 */
	public final TableField<FourItemsRecord, String> FILE_USER = createField("file_user", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>cbis.four_items.file_type</code>.
	 */
	public final TableField<FourItemsRecord, String> FILE_TYPE = createField("file_type", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * Create a <code>cbis.four_items</code> table reference
	 */
	public FourItems() {
		this("four_items", null);
	}

	/**
	 * Create an aliased <code>cbis.four_items</code> table reference
	 */
	public FourItems(String alias) {
		this(alias, FOUR_ITEMS);
	}

	private FourItems(String alias, Table<FourItemsRecord> aliased) {
		this(alias, aliased, null);
	}

	private FourItems(String alias, Table<FourItemsRecord> aliased, Field<?>[] parameters) {
		super(alias, Cbis.CBIS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<FourItemsRecord, Integer> getIdentity() {
		return Keys.IDENTITY_FOUR_ITEMS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<FourItemsRecord> getPrimaryKey() {
		return Keys.KEY_FOUR_ITEMS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<FourItemsRecord>> getKeys() {
		return Arrays.<UniqueKey<FourItemsRecord>>asList(Keys.KEY_FOUR_ITEMS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<FourItemsRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<FourItemsRecord, ?>>asList(Keys.FOUR_ITEMS_IBFK_1, Keys.FOUR_ITEMS_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FourItems as(String alias) {
		return new FourItems(alias, this);
	}

	/**
	 * Rename this table
	 */
	public FourItems rename(String name) {
		return new FourItems(name, null);
	}
}
