/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables;


import com.school.cbis.domain.Cbis;
import com.school.cbis.domain.Keys;
import com.school.cbis.domain.tables.records.MajorExamTrendsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MajorExamTrends extends TableImpl<MajorExamTrendsRecord> {

	private static final long serialVersionUID = 1495885329;

	/**
	 * The reference instance of <code>cbis.major_exam_trends</code>
	 */
	public static final MajorExamTrends MAJOR_EXAM_TRENDS = new MajorExamTrends();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MajorExamTrendsRecord> getRecordType() {
		return MajorExamTrendsRecord.class;
	}

	/**
	 * The column <code>cbis.major_exam_trends.id</code>.
	 */
	public final TableField<MajorExamTrendsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.major_exam_trends.major_id</code>.
	 */
	public final TableField<MajorExamTrendsRecord, Integer> MAJOR_ID = createField("major_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.major_exam_trends.exam_title</code>.
	 */
	public final TableField<MajorExamTrendsRecord, String> EXAM_TITLE = createField("exam_title", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>cbis.major_exam_trends.exam_start_time</code>.
	 */
	public final TableField<MajorExamTrendsRecord, Timestamp> EXAM_START_TIME = createField("exam_start_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>cbis.major_exam_trends.exam_end_time</code>.
	 */
	public final TableField<MajorExamTrendsRecord, Timestamp> EXAM_END_TIME = createField("exam_end_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>cbis.major_exam_trends.exam_place</code>.
	 */
	public final TableField<MajorExamTrendsRecord, String> EXAM_PLACE = createField("exam_place", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>cbis.major_exam_trends.exam_cotent</code>.
	 */
	public final TableField<MajorExamTrendsRecord, String> EXAM_COTENT = createField("exam_cotent", org.jooq.impl.SQLDataType.VARCHAR.length(600), this, "");

	/**
	 * The column <code>cbis.major_exam_trends.exam_announcements</code>.
	 */
	public final TableField<MajorExamTrendsRecord, String> EXAM_ANNOUNCEMENTS = createField("exam_announcements", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * Create a <code>cbis.major_exam_trends</code> table reference
	 */
	public MajorExamTrends() {
		this("major_exam_trends", null);
	}

	/**
	 * Create an aliased <code>cbis.major_exam_trends</code> table reference
	 */
	public MajorExamTrends(String alias) {
		this(alias, MAJOR_EXAM_TRENDS);
	}

	private MajorExamTrends(String alias, Table<MajorExamTrendsRecord> aliased) {
		this(alias, aliased, null);
	}

	private MajorExamTrends(String alias, Table<MajorExamTrendsRecord> aliased, Field<?>[] parameters) {
		super(alias, Cbis.CBIS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<MajorExamTrendsRecord, Integer> getIdentity() {
		return Keys.IDENTITY_MAJOR_EXAM_TRENDS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<MajorExamTrendsRecord> getPrimaryKey() {
		return Keys.KEY_MAJOR_EXAM_TRENDS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<MajorExamTrendsRecord>> getKeys() {
		return Arrays.<UniqueKey<MajorExamTrendsRecord>>asList(Keys.KEY_MAJOR_EXAM_TRENDS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<MajorExamTrendsRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<MajorExamTrendsRecord, ?>>asList(Keys.MAJOR_EXAM_TRENDS_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MajorExamTrends as(String alias) {
		return new MajorExamTrends(alias, this);
	}

	/**
	 * Rename this table
	 */
	public MajorExamTrends rename(String name) {
		return new MajorExamTrends(name, null);
	}
}
