/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables;


import com.school.cbis.domain.Cbis;
import com.school.cbis.domain.Keys;
import com.school.cbis.domain.tables.records.RelatedDownloadRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelatedDownload extends TableImpl<RelatedDownloadRecord> {

	private static final long serialVersionUID = -1869490614;

	/**
	 * The reference instance of <code>cbis.related_download</code>
	 */
	public static final RelatedDownload RELATED_DOWNLOAD = new RelatedDownload();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RelatedDownloadRecord> getRecordType() {
		return RelatedDownloadRecord.class;
	}

	/**
	 * The column <code>cbis.related_download.id</code>.
	 */
	public final TableField<RelatedDownloadRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.related_download.tie_id</code>.
	 */
	public final TableField<RelatedDownloadRecord, Integer> TIE_ID = createField("tie_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.related_download.file_url</code>.
	 */
	public final TableField<RelatedDownloadRecord, String> FILE_URL = createField("file_url", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false), this, "");

	/**
	 * The column <code>cbis.related_download.file_size</code>.
	 */
	public final TableField<RelatedDownloadRecord, String> FILE_SIZE = createField("file_size", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>cbis.related_download.file_name</code>.
	 */
	public final TableField<RelatedDownloadRecord, String> FILE_NAME = createField("file_name", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>cbis.related_download.file_date</code>.
	 */
	public final TableField<RelatedDownloadRecord, Timestamp> FILE_DATE = createField("file_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>cbis.related_download.file_down_times</code>.
	 */
	public final TableField<RelatedDownloadRecord, Integer> FILE_DOWN_TIMES = createField("file_down_times", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>cbis.related_download.teach_type_id</code>.
	 */
	public final TableField<RelatedDownloadRecord, Integer> TEACH_TYPE_ID = createField("teach_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.related_download.file_user</code>.
	 */
	public final TableField<RelatedDownloadRecord, String> FILE_USER = createField("file_user", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>cbis.related_download.file_type</code>.
	 */
	public final TableField<RelatedDownloadRecord, String> FILE_TYPE = createField("file_type", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>cbis.related_download.remark</code>.
	 */
	public final TableField<RelatedDownloadRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>cbis.related_download</code> table reference
	 */
	public RelatedDownload() {
		this("related_download", null);
	}

	/**
	 * Create an aliased <code>cbis.related_download</code> table reference
	 */
	public RelatedDownload(String alias) {
		this(alias, RELATED_DOWNLOAD);
	}

	private RelatedDownload(String alias, Table<RelatedDownloadRecord> aliased) {
		this(alias, aliased, null);
	}

	private RelatedDownload(String alias, Table<RelatedDownloadRecord> aliased, Field<?>[] parameters) {
		super(alias, Cbis.CBIS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<RelatedDownloadRecord, Integer> getIdentity() {
		return Keys.IDENTITY_RELATED_DOWNLOAD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RelatedDownloadRecord> getPrimaryKey() {
		return Keys.KEY_RELATED_DOWNLOAD_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RelatedDownloadRecord>> getKeys() {
		return Arrays.<UniqueKey<RelatedDownloadRecord>>asList(Keys.KEY_RELATED_DOWNLOAD_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<RelatedDownloadRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<RelatedDownloadRecord, ?>>asList(Keys.RELATED_DOWNLOAD_IBFK_1, Keys.RELATED_DOWNLOAD_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelatedDownload as(String alias) {
		return new RelatedDownload(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RelatedDownload rename(String name) {
		return new RelatedDownload(name, null);
	}
}
