/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables;


import com.school.cbis.domain.Cbis;
import com.school.cbis.domain.Keys;
import com.school.cbis.domain.tables.records.TeacherFillTaskContentRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherFillTaskContent extends TableImpl<TeacherFillTaskContentRecord> {

	private static final long serialVersionUID = 458435300;

	/**
	 * The reference instance of <code>cbis.teacher_fill_task_content</code>
	 */
	public static final TeacherFillTaskContent TEACHER_FILL_TASK_CONTENT = new TeacherFillTaskContent();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TeacherFillTaskContentRecord> getRecordType() {
		return TeacherFillTaskContentRecord.class;
	}

	/**
	 * The column <code>cbis.teacher_fill_task_content.id</code>.
	 */
	public final TableField<TeacherFillTaskContentRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.teacher_fill_task_content.content</code>.
	 */
	public final TableField<TeacherFillTaskContentRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * The column <code>cbis.teacher_fill_task_content.teacher_fill_task_head_id</code>.
	 */
	public final TableField<TeacherFillTaskContentRecord, Integer> TEACHER_FILL_TASK_HEAD_ID = createField("teacher_fill_task_head_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.teacher_fill_task_content.teacher_id</code>.
	 */
	public final TableField<TeacherFillTaskContentRecord, Integer> TEACHER_ID = createField("teacher_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.teacher_fill_task_content.teacher_fill_task_info_id</code>.
	 */
	public final TableField<TeacherFillTaskContentRecord, Integer> TEACHER_FILL_TASK_INFO_ID = createField("teacher_fill_task_info_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>cbis.teacher_fill_task_content</code> table reference
	 */
	public TeacherFillTaskContent() {
		this("teacher_fill_task_content", null);
	}

	/**
	 * Create an aliased <code>cbis.teacher_fill_task_content</code> table reference
	 */
	public TeacherFillTaskContent(String alias) {
		this(alias, TEACHER_FILL_TASK_CONTENT);
	}

	private TeacherFillTaskContent(String alias, Table<TeacherFillTaskContentRecord> aliased) {
		this(alias, aliased, null);
	}

	private TeacherFillTaskContent(String alias, Table<TeacherFillTaskContentRecord> aliased, Field<?>[] parameters) {
		super(alias, Cbis.CBIS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<TeacherFillTaskContentRecord, Integer> getIdentity() {
		return Keys.IDENTITY_TEACHER_FILL_TASK_CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TeacherFillTaskContentRecord> getPrimaryKey() {
		return Keys.KEY_TEACHER_FILL_TASK_CONTENT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TeacherFillTaskContentRecord>> getKeys() {
		return Arrays.<UniqueKey<TeacherFillTaskContentRecord>>asList(Keys.KEY_TEACHER_FILL_TASK_CONTENT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<TeacherFillTaskContentRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<TeacherFillTaskContentRecord, ?>>asList(Keys.TEACHER_FILL_TASK_CONTENT_IBFK_1, Keys.TEACHER_FILL_TASK_CONTENT_IBFK_2, Keys.TEACHER_FILL_TASK_CONTENT_IBFK_3);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherFillTaskContent as(String alias) {
		return new TeacherFillTaskContent(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TeacherFillTaskContent rename(String name) {
		return new TeacherFillTaskContent(name, null);
	}
}
