/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables;


import com.school.cbis.domain.Cbis;
import com.school.cbis.domain.Keys;
import com.school.cbis.domain.tables.records.TeacherCourseTimetableInfoRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherCourseTimetableInfo extends TableImpl<TeacherCourseTimetableInfoRecord> {

	private static final long serialVersionUID = 1984736075;

	/**
	 * The reference instance of <code>cbis.teacher_course_timetable_info</code>
	 */
	public static final TeacherCourseTimetableInfo TEACHER_COURSE_TIMETABLE_INFO = new TeacherCourseTimetableInfo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TeacherCourseTimetableInfoRecord> getRecordType() {
		return TeacherCourseTimetableInfoRecord.class;
	}

	/**
	 * The column <code>cbis.teacher_course_timetable_info.id</code>.
	 */
	public final TableField<TeacherCourseTimetableInfoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.teacher_course_timetable_info.tie_id</code>.
	 */
	public final TableField<TeacherCourseTimetableInfoRecord, Integer> TIE_ID = createField("tie_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.teacher_course_timetable_info.timetable_info_term</code>.
	 */
	public final TableField<TeacherCourseTimetableInfoRecord, String> TIMETABLE_INFO_TERM = createField("timetable_info_term", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>cbis.teacher_course_timetable_info.timetable_info_file_url</code>.
	 */
	public final TableField<TeacherCourseTimetableInfoRecord, String> TIMETABLE_INFO_FILE_URL = createField("timetable_info_file_url", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false), this, "");

	/**
	 * The column <code>cbis.teacher_course_timetable_info.timetable_info_file_pdf</code>.
	 */
	public final TableField<TeacherCourseTimetableInfoRecord, String> TIMETABLE_INFO_FILE_PDF = createField("timetable_info_file_pdf", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * The column <code>cbis.teacher_course_timetable_info.timetable_info_file_name</code>.
	 */
	public final TableField<TeacherCourseTimetableInfoRecord, String> TIMETABLE_INFO_FILE_NAME = createField("timetable_info_file_name", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>cbis.teacher_course_timetable_info.timetable_info_file_date</code>.
	 */
	public final TableField<TeacherCourseTimetableInfoRecord, Timestamp> TIMETABLE_INFO_FILE_DATE = createField("timetable_info_file_date", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>cbis.teacher_course_timetable_info.timetable_info_file_down_times</code>.
	 */
	public final TableField<TeacherCourseTimetableInfoRecord, Integer> TIMETABLE_INFO_FILE_DOWN_TIMES = createField("timetable_info_file_down_times", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>cbis.teacher_course_timetable_info.teach_type_id</code>.
	 */
	public final TableField<TeacherCourseTimetableInfoRecord, Integer> TEACH_TYPE_ID = createField("teach_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.teacher_course_timetable_info.term_start_time</code>.
	 */
	public final TableField<TeacherCourseTimetableInfoRecord, Date> TERM_START_TIME = createField("term_start_time", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>cbis.teacher_course_timetable_info.term_end_time</code>.
	 */
	public final TableField<TeacherCourseTimetableInfoRecord, Date> TERM_END_TIME = createField("term_end_time", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>cbis.teacher_course_timetable_info.file_user</code>.
	 */
	public final TableField<TeacherCourseTimetableInfoRecord, String> FILE_USER = createField("file_user", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>cbis.teacher_course_timetable_info.file_type</code>.
	 */
	public final TableField<TeacherCourseTimetableInfoRecord, String> FILE_TYPE = createField("file_type", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * Create a <code>cbis.teacher_course_timetable_info</code> table reference
	 */
	public TeacherCourseTimetableInfo() {
		this("teacher_course_timetable_info", null);
	}

	/**
	 * Create an aliased <code>cbis.teacher_course_timetable_info</code> table reference
	 */
	public TeacherCourseTimetableInfo(String alias) {
		this(alias, TEACHER_COURSE_TIMETABLE_INFO);
	}

	private TeacherCourseTimetableInfo(String alias, Table<TeacherCourseTimetableInfoRecord> aliased) {
		this(alias, aliased, null);
	}

	private TeacherCourseTimetableInfo(String alias, Table<TeacherCourseTimetableInfoRecord> aliased, Field<?>[] parameters) {
		super(alias, Cbis.CBIS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<TeacherCourseTimetableInfoRecord, Integer> getIdentity() {
		return Keys.IDENTITY_TEACHER_COURSE_TIMETABLE_INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TeacherCourseTimetableInfoRecord> getPrimaryKey() {
		return Keys.KEY_TEACHER_COURSE_TIMETABLE_INFO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TeacherCourseTimetableInfoRecord>> getKeys() {
		return Arrays.<UniqueKey<TeacherCourseTimetableInfoRecord>>asList(Keys.KEY_TEACHER_COURSE_TIMETABLE_INFO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<TeacherCourseTimetableInfoRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<TeacherCourseTimetableInfoRecord, ?>>asList(Keys.TEACHER_COURSE_TIMETABLE_INFO_IBFK_1, Keys.TEACHER_COURSE_TIMETABLE_INFO_IBFK_2, Keys.TEACHER_COURSE_TIMETABLE_INFO_IBFK_3);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeacherCourseTimetableInfo as(String alias) {
		return new TeacherCourseTimetableInfo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TeacherCourseTimetableInfo rename(String name) {
		return new TeacherCourseTimetableInfo(name, null);
	}
}
