/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables;


import com.school.cbis.domain.Cbis;
import com.school.cbis.domain.Keys;
import com.school.cbis.domain.tables.records.TeachingMaterialInfoRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeachingMaterialInfo extends TableImpl<TeachingMaterialInfoRecord> {

	private static final long serialVersionUID = 1277054610;

	/**
	 * The reference instance of <code>cbis.teaching_material_info</code>
	 */
	public static final TeachingMaterialInfo TEACHING_MATERIAL_INFO = new TeachingMaterialInfo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TeachingMaterialInfoRecord> getRecordType() {
		return TeachingMaterialInfoRecord.class;
	}

	/**
	 * The column <code>cbis.teaching_material_info.id</code>.
	 */
	public final TableField<TeachingMaterialInfoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.teaching_material_info.title</code>.
	 */
	public final TableField<TeachingMaterialInfoRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>cbis.teaching_material_info.create_time</code>.
	 */
	public final TableField<TeachingMaterialInfoRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>cbis.teaching_material_info.teaching_material_template_id</code>.
	 */
	public final TableField<TeachingMaterialInfoRecord, Integer> TEACHING_MATERIAL_TEMPLATE_ID = createField("teaching_material_template_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.teaching_material_info.start_time</code>.
	 */
	public final TableField<TeachingMaterialInfoRecord, Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>cbis.teaching_material_info.end_time</code>.
	 */
	public final TableField<TeachingMaterialInfoRecord, Timestamp> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>cbis.teaching_material_info.users_id</code>.
	 */
	public final TableField<TeachingMaterialInfoRecord, String> USERS_ID = createField("users_id", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>cbis.teaching_material_info.tie_id</code>.
	 */
	public final TableField<TeachingMaterialInfoRecord, Integer> TIE_ID = createField("tie_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>cbis.teaching_material_info</code> table reference
	 */
	public TeachingMaterialInfo() {
		this("teaching_material_info", null);
	}

	/**
	 * Create an aliased <code>cbis.teaching_material_info</code> table reference
	 */
	public TeachingMaterialInfo(String alias) {
		this(alias, TEACHING_MATERIAL_INFO);
	}

	private TeachingMaterialInfo(String alias, Table<TeachingMaterialInfoRecord> aliased) {
		this(alias, aliased, null);
	}

	private TeachingMaterialInfo(String alias, Table<TeachingMaterialInfoRecord> aliased, Field<?>[] parameters) {
		super(alias, Cbis.CBIS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<TeachingMaterialInfoRecord, Integer> getIdentity() {
		return Keys.IDENTITY_TEACHING_MATERIAL_INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TeachingMaterialInfoRecord> getPrimaryKey() {
		return Keys.KEY_TEACHING_MATERIAL_INFO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TeachingMaterialInfoRecord>> getKeys() {
		return Arrays.<UniqueKey<TeachingMaterialInfoRecord>>asList(Keys.KEY_TEACHING_MATERIAL_INFO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<TeachingMaterialInfoRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<TeachingMaterialInfoRecord, ?>>asList(Keys.TEACHING_MATERIAL_INFO_IBFK_1, Keys.TEACHING_MATERIAL_INFO_IBFK_2, Keys.TEACHING_MATERIAL_INFO_IBFK_3);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachingMaterialInfo as(String alias) {
		return new TeachingMaterialInfo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TeachingMaterialInfo rename(String name) {
		return new TeachingMaterialInfo(name, null);
	}
}
