/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables;


import com.school.cbis.domain.Cbis;
import com.school.cbis.domain.Keys;
import com.school.cbis.domain.tables.records.TeachTypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeachType extends TableImpl<TeachTypeRecord> {

	private static final long serialVersionUID = 1483640050;

	/**
	 * The reference instance of <code>cbis.teach_type</code>
	 */
	public static final TeachType TEACH_TYPE = new TeachType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TeachTypeRecord> getRecordType() {
		return TeachTypeRecord.class;
	}

	/**
	 * The column <code>cbis.teach_type.id</code>.
	 */
	public final TableField<TeachTypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.teach_type.name</code>.
	 */
	public final TableField<TeachTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

	/**
	 * Create a <code>cbis.teach_type</code> table reference
	 */
	public TeachType() {
		this("teach_type", null);
	}

	/**
	 * Create an aliased <code>cbis.teach_type</code> table reference
	 */
	public TeachType(String alias) {
		this(alias, TEACH_TYPE);
	}

	private TeachType(String alias, Table<TeachTypeRecord> aliased) {
		this(alias, aliased, null);
	}

	private TeachType(String alias, Table<TeachTypeRecord> aliased, Field<?>[] parameters) {
		super(alias, Cbis.CBIS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<TeachTypeRecord, Integer> getIdentity() {
		return Keys.IDENTITY_TEACH_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TeachTypeRecord> getPrimaryKey() {
		return Keys.KEY_TEACH_TYPE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TeachTypeRecord>> getKeys() {
		return Arrays.<UniqueKey<TeachTypeRecord>>asList(Keys.KEY_TEACH_TYPE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TeachType as(String alias) {
		return new TeachType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TeachType rename(String name) {
		return new TeachType(name, null);
	}
}
