/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables;


import com.school.cbis.domain.Cbis;
import com.school.cbis.domain.Keys;
import com.school.cbis.domain.tables.records.TieElegantTimeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TieElegantTime extends TableImpl<TieElegantTimeRecord> {

	private static final long serialVersionUID = 227218756;

	/**
	 * The reference instance of <code>cbis.tie_elegant_time</code>
	 */
	public static final TieElegantTime TIE_ELEGANT_TIME = new TieElegantTime();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TieElegantTimeRecord> getRecordType() {
		return TieElegantTimeRecord.class;
	}

	/**
	 * The column <code>cbis.tie_elegant_time.id</code>.
	 */
	public final TableField<TieElegantTimeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.tie_elegant_time.time</code>.
	 */
	public final TableField<TieElegantTimeRecord, String> TIME = createField("time", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

	/**
	 * Create a <code>cbis.tie_elegant_time</code> table reference
	 */
	public TieElegantTime() {
		this("tie_elegant_time", null);
	}

	/**
	 * Create an aliased <code>cbis.tie_elegant_time</code> table reference
	 */
	public TieElegantTime(String alias) {
		this(alias, TIE_ELEGANT_TIME);
	}

	private TieElegantTime(String alias, Table<TieElegantTimeRecord> aliased) {
		this(alias, aliased, null);
	}

	private TieElegantTime(String alias, Table<TieElegantTimeRecord> aliased, Field<?>[] parameters) {
		super(alias, Cbis.CBIS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<TieElegantTimeRecord, Integer> getIdentity() {
		return Keys.IDENTITY_TIE_ELEGANT_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TieElegantTimeRecord> getPrimaryKey() {
		return Keys.KEY_TIE_ELEGANT_TIME_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TieElegantTimeRecord>> getKeys() {
		return Arrays.<UniqueKey<TieElegantTimeRecord>>asList(Keys.KEY_TIE_ELEGANT_TIME_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TieElegantTime as(String alias) {
		return new TieElegantTime(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TieElegantTime rename(String name) {
		return new TieElegantTime(name, null);
	}
}
