/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables;


import com.school.cbis.domain.Cbis;
import com.school.cbis.domain.Keys;
import com.school.cbis.domain.tables.records.YardRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Yard extends TableImpl<YardRecord> {

	private static final long serialVersionUID = 1423904397;

	/**
	 * The reference instance of <code>cbis.yard</code>
	 */
	public static final Yard YARD = new Yard();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<YardRecord> getRecordType() {
		return YardRecord.class;
	}

	/**
	 * The column <code>cbis.yard.id</code>.
	 */
	public final TableField<YardRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>cbis.yard.yard_name</code>.
	 */
	public final TableField<YardRecord, String> YARD_NAME = createField("yard_name", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>cbis.yard.yard_address</code>.
	 */
	public final TableField<YardRecord, String> YARD_ADDRESS = createField("yard_address", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * Create a <code>cbis.yard</code> table reference
	 */
	public Yard() {
		this("yard", null);
	}

	/**
	 * Create an aliased <code>cbis.yard</code> table reference
	 */
	public Yard(String alias) {
		this(alias, YARD);
	}

	private Yard(String alias, Table<YardRecord> aliased) {
		this(alias, aliased, null);
	}

	private Yard(String alias, Table<YardRecord> aliased, Field<?>[] parameters) {
		super(alias, Cbis.CBIS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<YardRecord, Integer> getIdentity() {
		return Keys.IDENTITY_YARD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<YardRecord> getPrimaryKey() {
		return Keys.KEY_YARD_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<YardRecord>> getKeys() {
		return Arrays.<UniqueKey<YardRecord>>asList(Keys.KEY_YARD_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Yard as(String alias) {
		return new Yard(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Yard rename(String name) {
		return new Yard(name, null);
	}
}
