/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleSub implements Serializable {

	private static final long serialVersionUID = 2044665546;

	private Integer id;
	private String  subTitle;
	private String  subContent;
	private Integer articleInfoId;

	public ArticleSub() {}

	public ArticleSub(ArticleSub value) {
		this.id = value.id;
		this.subTitle = value.subTitle;
		this.subContent = value.subContent;
		this.articleInfoId = value.articleInfoId;
	}

	public ArticleSub(
		Integer id,
		String  subTitle,
		String  subContent,
		Integer articleInfoId
	) {
		this.id = id;
		this.subTitle = subTitle;
		this.subContent = subContent;
		this.articleInfoId = articleInfoId;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Size(max = 50)
	public String getSubTitle() {
		return this.subTitle;
	}

	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}

	@Size(max = 1000)
	public String getSubContent() {
		return this.subContent;
	}

	public void setSubContent(String subContent) {
		this.subContent = subContent;
	}

	@NotNull
	public Integer getArticleInfoId() {
		return this.articleInfoId;
	}

	public void setArticleInfoId(Integer articleInfoId) {
		this.articleInfoId = articleInfoId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("ArticleSub (");

		sb.append(id);
		sb.append(", ").append(subTitle);
		sb.append(", ").append(subContent);
		sb.append(", ").append(articleInfoId);

		sb.append(")");
		return sb.toString();
	}
}
