/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutonomousPracticeHead implements Serializable {

	private static final long serialVersionUID = -1885127479;

	private Integer id;
	private String  title;
	private String  titleVariable;
	private String  databaseTable;
	private String  databaseTableField;
	private String  authority;
	private String  headTypePluginFiled;
	private Byte    isEditing;
	private Byte    isFiltering;
	private Byte    isSorting;
	private Byte    isVisible;
	private String  headTypePlugingContent;
	private Byte    isShowHighlyActive;
	private Byte    isShowGeneral;
	private String  highlyActiveAuthority;
	private String  generalAuthority;
	private Byte    isRequired;
	private Integer headTypeId;
	private Integer autonomousPracticeInfoId;

	public AutonomousPracticeHead() {}

	public AutonomousPracticeHead(AutonomousPracticeHead value) {
		this.id = value.id;
		this.title = value.title;
		this.titleVariable = value.titleVariable;
		this.databaseTable = value.databaseTable;
		this.databaseTableField = value.databaseTableField;
		this.authority = value.authority;
		this.headTypePluginFiled = value.headTypePluginFiled;
		this.isEditing = value.isEditing;
		this.isFiltering = value.isFiltering;
		this.isSorting = value.isSorting;
		this.isVisible = value.isVisible;
		this.headTypePlugingContent = value.headTypePlugingContent;
		this.isShowHighlyActive = value.isShowHighlyActive;
		this.isShowGeneral = value.isShowGeneral;
		this.highlyActiveAuthority = value.highlyActiveAuthority;
		this.generalAuthority = value.generalAuthority;
		this.isRequired = value.isRequired;
		this.headTypeId = value.headTypeId;
		this.autonomousPracticeInfoId = value.autonomousPracticeInfoId;
	}

	public AutonomousPracticeHead(
		Integer id,
		String  title,
		String  titleVariable,
		String  databaseTable,
		String  databaseTableField,
		String  authority,
		String  headTypePluginFiled,
		Byte    isEditing,
		Byte    isFiltering,
		Byte    isSorting,
		Byte    isVisible,
		String  headTypePlugingContent,
		Byte    isShowHighlyActive,
		Byte    isShowGeneral,
		String  highlyActiveAuthority,
		String  generalAuthority,
		Byte    isRequired,
		Integer headTypeId,
		Integer autonomousPracticeInfoId
	) {
		this.id = id;
		this.title = title;
		this.titleVariable = titleVariable;
		this.databaseTable = databaseTable;
		this.databaseTableField = databaseTableField;
		this.authority = authority;
		this.headTypePluginFiled = headTypePluginFiled;
		this.isEditing = isEditing;
		this.isFiltering = isFiltering;
		this.isSorting = isSorting;
		this.isVisible = isVisible;
		this.headTypePlugingContent = headTypePlugingContent;
		this.isShowHighlyActive = isShowHighlyActive;
		this.isShowGeneral = isShowGeneral;
		this.highlyActiveAuthority = highlyActiveAuthority;
		this.generalAuthority = generalAuthority;
		this.isRequired = isRequired;
		this.headTypeId = headTypeId;
		this.autonomousPracticeInfoId = autonomousPracticeInfoId;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@NotNull
	@Size(max = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@NotNull
	@Size(max = 50)
	public String getTitleVariable() {
		return this.titleVariable;
	}

	public void setTitleVariable(String titleVariable) {
		this.titleVariable = titleVariable;
	}

	@NotNull
	@Size(max = 100)
	public String getDatabaseTable() {
		return this.databaseTable;
	}

	public void setDatabaseTable(String databaseTable) {
		this.databaseTable = databaseTable;
	}

	@NotNull
	@Size(max = 100)
	public String getDatabaseTableField() {
		return this.databaseTableField;
	}

	public void setDatabaseTableField(String databaseTableField) {
		this.databaseTableField = databaseTableField;
	}

	@NotNull
	@Size(max = 30)
	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

	@Size(max = 30)
	public String getHeadTypePluginFiled() {
		return this.headTypePluginFiled;
	}

	public void setHeadTypePluginFiled(String headTypePluginFiled) {
		this.headTypePluginFiled = headTypePluginFiled;
	}

	@NotNull
	public Byte getIsEditing() {
		return this.isEditing;
	}

	public void setIsEditing(Byte isEditing) {
		this.isEditing = isEditing;
	}

	@NotNull
	public Byte getIsFiltering() {
		return this.isFiltering;
	}

	public void setIsFiltering(Byte isFiltering) {
		this.isFiltering = isFiltering;
	}

	@NotNull
	public Byte getIsSorting() {
		return this.isSorting;
	}

	public void setIsSorting(Byte isSorting) {
		this.isSorting = isSorting;
	}

	@NotNull
	public Byte getIsVisible() {
		return this.isVisible;
	}

	public void setIsVisible(Byte isVisible) {
		this.isVisible = isVisible;
	}

	@Size(max = 2000)
	public String getHeadTypePlugingContent() {
		return this.headTypePlugingContent;
	}

	public void setHeadTypePlugingContent(String headTypePlugingContent) {
		this.headTypePlugingContent = headTypePlugingContent;
	}

	@NotNull
	public Byte getIsShowHighlyActive() {
		return this.isShowHighlyActive;
	}

	public void setIsShowHighlyActive(Byte isShowHighlyActive) {
		this.isShowHighlyActive = isShowHighlyActive;
	}

	@NotNull
	public Byte getIsShowGeneral() {
		return this.isShowGeneral;
	}

	public void setIsShowGeneral(Byte isShowGeneral) {
		this.isShowGeneral = isShowGeneral;
	}

	@NotNull
	@Size(max = 30)
	public String getHighlyActiveAuthority() {
		return this.highlyActiveAuthority;
	}

	public void setHighlyActiveAuthority(String highlyActiveAuthority) {
		this.highlyActiveAuthority = highlyActiveAuthority;
	}

	@NotNull
	@Size(max = 30)
	public String getGeneralAuthority() {
		return this.generalAuthority;
	}

	public void setGeneralAuthority(String generalAuthority) {
		this.generalAuthority = generalAuthority;
	}

	@NotNull
	public Byte getIsRequired() {
		return this.isRequired;
	}

	public void setIsRequired(Byte isRequired) {
		this.isRequired = isRequired;
	}

	@NotNull
	public Integer getHeadTypeId() {
		return this.headTypeId;
	}

	public void setHeadTypeId(Integer headTypeId) {
		this.headTypeId = headTypeId;
	}

	@NotNull
	public Integer getAutonomousPracticeInfoId() {
		return this.autonomousPracticeInfoId;
	}

	public void setAutonomousPracticeInfoId(Integer autonomousPracticeInfoId) {
		this.autonomousPracticeInfoId = autonomousPracticeInfoId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("AutonomousPracticeHead (");

		sb.append(id);
		sb.append(", ").append(title);
		sb.append(", ").append(titleVariable);
		sb.append(", ").append(databaseTable);
		sb.append(", ").append(databaseTableField);
		sb.append(", ").append(authority);
		sb.append(", ").append(headTypePluginFiled);
		sb.append(", ").append(isEditing);
		sb.append(", ").append(isFiltering);
		sb.append(", ").append(isSorting);
		sb.append(", ").append(isVisible);
		sb.append(", ").append(headTypePlugingContent);
		sb.append(", ").append(isShowHighlyActive);
		sb.append(", ").append(isShowGeneral);
		sb.append(", ").append(highlyActiveAuthority);
		sb.append(", ").append(generalAuthority);
		sb.append(", ").append(isRequired);
		sb.append(", ").append(headTypeId);
		sb.append(", ").append(autonomousPracticeInfoId);

		sb.append(")");
		return sb.toString();
	}
}
