/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutonomousPracticeContent implements Serializable {

	private static final long serialVersionUID = 2087547425;

	private Integer id;
	private String  content;
	private Integer autonomousPracticeHeadId;
	private Integer studentId;

	public AutonomousPracticeContent() {}

	public AutonomousPracticeContent(AutonomousPracticeContent value) {
		this.id = value.id;
		this.content = value.content;
		this.autonomousPracticeHeadId = value.autonomousPracticeHeadId;
		this.studentId = value.studentId;
	}

	public AutonomousPracticeContent(
		Integer id,
		String  content,
		Integer autonomousPracticeHeadId,
		Integer studentId
	) {
		this.id = id;
		this.content = content;
		this.autonomousPracticeHeadId = autonomousPracticeHeadId;
		this.studentId = studentId;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Size(max = 500)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@NotNull
	public Integer getAutonomousPracticeHeadId() {
		return this.autonomousPracticeHeadId;
	}

	public void setAutonomousPracticeHeadId(Integer autonomousPracticeHeadId) {
		this.autonomousPracticeHeadId = autonomousPracticeHeadId;
	}

	@NotNull
	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("AutonomousPracticeContent (");

		sb.append(id);
		sb.append(", ").append(content);
		sb.append(", ").append(autonomousPracticeHeadId);
		sb.append(", ").append(studentId);

		sb.append(")");
		return sb.toString();
	}
}
