/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutonomousPracticeTemplate implements Serializable {

	private static final long serialVersionUID = -2143610585;

	private Integer   id;
	private String    autonomousPracticeTemplateTitle;
	private Timestamp createTime;
	private Integer   autonomousPracticeInfoId;

	public AutonomousPracticeTemplate() {}

	public AutonomousPracticeTemplate(AutonomousPracticeTemplate value) {
		this.id = value.id;
		this.autonomousPracticeTemplateTitle = value.autonomousPracticeTemplateTitle;
		this.createTime = value.createTime;
		this.autonomousPracticeInfoId = value.autonomousPracticeInfoId;
	}

	public AutonomousPracticeTemplate(
		Integer   id,
		String    autonomousPracticeTemplateTitle,
		Timestamp createTime,
		Integer   autonomousPracticeInfoId
	) {
		this.id = id;
		this.autonomousPracticeTemplateTitle = autonomousPracticeTemplateTitle;
		this.createTime = createTime;
		this.autonomousPracticeInfoId = autonomousPracticeInfoId;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@NotNull
	@Size(max = 50)
	public String getAutonomousPracticeTemplateTitle() {
		return this.autonomousPracticeTemplateTitle;
	}

	public void setAutonomousPracticeTemplateTitle(String autonomousPracticeTemplateTitle) {
		this.autonomousPracticeTemplateTitle = autonomousPracticeTemplateTitle;
	}

	@NotNull
	public Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	@NotNull
	public Integer getAutonomousPracticeInfoId() {
		return this.autonomousPracticeInfoId;
	}

	public void setAutonomousPracticeInfoId(Integer autonomousPracticeInfoId) {
		this.autonomousPracticeInfoId = autonomousPracticeInfoId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("AutonomousPracticeTemplate (");

		sb.append(id);
		sb.append(", ").append(autonomousPracticeTemplateTitle);
		sb.append(", ").append(createTime);
		sb.append(", ").append(autonomousPracticeInfoId);

		sb.append(")");
		return sb.toString();
	}
}
