/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HeadTypePlugin implements Serializable {

	private static final long serialVersionUID = -2040554;

	private Integer id;
	private String  type;
	private String  content;
	private Integer headTypeId;

	public HeadTypePlugin() {}

	public HeadTypePlugin(HeadTypePlugin value) {
		this.id = value.id;
		this.type = value.type;
		this.content = value.content;
		this.headTypeId = value.headTypeId;
	}

	public HeadTypePlugin(
		Integer id,
		String  type,
		String  content,
		Integer headTypeId
	) {
		this.id = id;
		this.type = type;
		this.content = content;
		this.headTypeId = headTypeId;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@NotNull
	@Size(max = 25)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@NotNull
	@Size(max = 500)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@NotNull
	public Integer getHeadTypeId() {
		return this.headTypeId;
	}

	public void setHeadTypeId(Integer headTypeId) {
		this.headTypeId = headTypeId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("HeadTypePlugin (");

		sb.append(id);
		sb.append(", ").append(type);
		sb.append(", ").append(content);
		sb.append(", ").append(headTypeId);

		sb.append(")");
		return sb.toString();
	}
}
