/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlaceFileInfo implements Serializable {

	private static final long serialVersionUID = 2079430383;

	private Integer   id;
	private Integer   teachTaskInfoId;
	private String    placeFileInfoUrl;
	private String    placeFileInfoSize;
	private String    placeFileInfoName;
	private Timestamp placeFileInfoDate;
	private String    fileUser;
	private String    fileType;

	public PlaceFileInfo() {}

	public PlaceFileInfo(PlaceFileInfo value) {
		this.id = value.id;
		this.teachTaskInfoId = value.teachTaskInfoId;
		this.placeFileInfoUrl = value.placeFileInfoUrl;
		this.placeFileInfoSize = value.placeFileInfoSize;
		this.placeFileInfoName = value.placeFileInfoName;
		this.placeFileInfoDate = value.placeFileInfoDate;
		this.fileUser = value.fileUser;
		this.fileType = value.fileType;
	}

	public PlaceFileInfo(
		Integer   id,
		Integer   teachTaskInfoId,
		String    placeFileInfoUrl,
		String    placeFileInfoSize,
		String    placeFileInfoName,
		Timestamp placeFileInfoDate,
		String    fileUser,
		String    fileType
	) {
		this.id = id;
		this.teachTaskInfoId = teachTaskInfoId;
		this.placeFileInfoUrl = placeFileInfoUrl;
		this.placeFileInfoSize = placeFileInfoSize;
		this.placeFileInfoName = placeFileInfoName;
		this.placeFileInfoDate = placeFileInfoDate;
		this.fileUser = fileUser;
		this.fileType = fileType;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@NotNull
	public Integer getTeachTaskInfoId() {
		return this.teachTaskInfoId;
	}

	public void setTeachTaskInfoId(Integer teachTaskInfoId) {
		this.teachTaskInfoId = teachTaskInfoId;
	}

	@NotNull
	@Size(max = 500)
	public String getPlaceFileInfoUrl() {
		return this.placeFileInfoUrl;
	}

	public void setPlaceFileInfoUrl(String placeFileInfoUrl) {
		this.placeFileInfoUrl = placeFileInfoUrl;
	}

	@Size(max = 50)
	public String getPlaceFileInfoSize() {
		return this.placeFileInfoSize;
	}

	public void setPlaceFileInfoSize(String placeFileInfoSize) {
		this.placeFileInfoSize = placeFileInfoSize;
	}

	@NotNull
	@Size(max = 30)
	public String getPlaceFileInfoName() {
		return this.placeFileInfoName;
	}

	public void setPlaceFileInfoName(String placeFileInfoName) {
		this.placeFileInfoName = placeFileInfoName;
	}

	public Timestamp getPlaceFileInfoDate() {
		return this.placeFileInfoDate;
	}

	public void setPlaceFileInfoDate(Timestamp placeFileInfoDate) {
		this.placeFileInfoDate = placeFileInfoDate;
	}

	@NotNull
	@Size(max = 64)
	public String getFileUser() {
		return this.fileUser;
	}

	public void setFileUser(String fileUser) {
		this.fileUser = fileUser;
	}

	@Size(max = 15)
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("PlaceFileInfo (");

		sb.append(id);
		sb.append(", ").append(teachTaskInfoId);
		sb.append(", ").append(placeFileInfoUrl);
		sb.append(", ").append(placeFileInfoSize);
		sb.append(", ").append(placeFileInfoName);
		sb.append(", ").append(placeFileInfoDate);
		sb.append(", ").append(fileUser);
		sb.append(", ").append(fileType);

		sb.append(")");
		return sb.toString();
	}
}
