/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemLog implements Serializable {

	private static final long serialVersionUID = -1010821840;

	private Integer   id;
	private String    username;
	private String    operationBehavior;
	private Timestamp createTime;
	private Integer   tieId;

	public SystemLog() {}

	public SystemLog(SystemLog value) {
		this.id = value.id;
		this.username = value.username;
		this.operationBehavior = value.operationBehavior;
		this.createTime = value.createTime;
		this.tieId = value.tieId;
	}

	public SystemLog(
		Integer   id,
		String    username,
		String    operationBehavior,
		Timestamp createTime,
		Integer   tieId
	) {
		this.id = id;
		this.username = username;
		this.operationBehavior = operationBehavior;
		this.createTime = createTime;
		this.tieId = tieId;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@NotNull
	@Size(max = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Size(max = 200)
	public String getOperationBehavior() {
		return this.operationBehavior;
	}

	public void setOperationBehavior(String operationBehavior) {
		this.operationBehavior = operationBehavior;
	}

	@NotNull
	public Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	@NotNull
	public Integer getTieId() {
		return this.tieId;
	}

	public void setTieId(Integer tieId) {
		this.tieId = tieId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("SystemLog (");

		sb.append(id);
		sb.append(", ").append(username);
		sb.append(", ").append(operationBehavior);
		sb.append(", ").append(createTime);
		sb.append(", ").append(tieId);

		sb.append(")");
		return sb.toString();
	}
}
