/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Teacher implements Serializable {

	private static final long serialVersionUID = -785185249;

	private Integer id;
	private Integer tieId;
	private String  teacherJobNumber;
	private Integer teacherIntroduceArticleInfoId;

	public Teacher() {}

	public Teacher(Teacher value) {
		this.id = value.id;
		this.tieId = value.tieId;
		this.teacherJobNumber = value.teacherJobNumber;
		this.teacherIntroduceArticleInfoId = value.teacherIntroduceArticleInfoId;
	}

	public Teacher(
		Integer id,
		Integer tieId,
		String  teacherJobNumber,
		Integer teacherIntroduceArticleInfoId
	) {
		this.id = id;
		this.tieId = tieId;
		this.teacherJobNumber = teacherJobNumber;
		this.teacherIntroduceArticleInfoId = teacherIntroduceArticleInfoId;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@NotNull
	public Integer getTieId() {
		return this.tieId;
	}

	public void setTieId(Integer tieId) {
		this.tieId = tieId;
	}

	@NotNull
	@Size(max = 25)
	public String getTeacherJobNumber() {
		return this.teacherJobNumber;
	}

	public void setTeacherJobNumber(String teacherJobNumber) {
		this.teacherJobNumber = teacherJobNumber;
	}

	public Integer getTeacherIntroduceArticleInfoId() {
		return this.teacherIntroduceArticleInfoId;
	}

	public void setTeacherIntroduceArticleInfoId(Integer teacherIntroduceArticleInfoId) {
		this.teacherIntroduceArticleInfoId = teacherIntroduceArticleInfoId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Teacher (");

		sb.append(id);
		sb.append(", ").append(tieId);
		sb.append(", ").append(teacherJobNumber);
		sb.append(", ").append(teacherIntroduceArticleInfoId);

		sb.append(")");
		return sb.toString();
	}
}
