/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherFillTaskInfo implements Serializable {

	private static final long serialVersionUID = 2088993136;

	private Integer   id;
	private String    title;
	private Timestamp createTime;
	private Integer   teacherFillTaskTemplateId;
	private Timestamp startTime;
	private Timestamp endTime;
	private String    usersId;
	private Integer   tieId;
	private Byte      isOk;

	public TeacherFillTaskInfo() {}

	public TeacherFillTaskInfo(TeacherFillTaskInfo value) {
		this.id = value.id;
		this.title = value.title;
		this.createTime = value.createTime;
		this.teacherFillTaskTemplateId = value.teacherFillTaskTemplateId;
		this.startTime = value.startTime;
		this.endTime = value.endTime;
		this.usersId = value.usersId;
		this.tieId = value.tieId;
		this.isOk = value.isOk;
	}

	public TeacherFillTaskInfo(
		Integer   id,
		String    title,
		Timestamp createTime,
		Integer   teacherFillTaskTemplateId,
		Timestamp startTime,
		Timestamp endTime,
		String    usersId,
		Integer   tieId,
		Byte      isOk
	) {
		this.id = id;
		this.title = title;
		this.createTime = createTime;
		this.teacherFillTaskTemplateId = teacherFillTaskTemplateId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.usersId = usersId;
		this.tieId = tieId;
		this.isOk = isOk;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@NotNull
	@Size(max = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@NotNull
	public Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	@NotNull
	public Integer getTeacherFillTaskTemplateId() {
		return this.teacherFillTaskTemplateId;
	}

	public void setTeacherFillTaskTemplateId(Integer teacherFillTaskTemplateId) {
		this.teacherFillTaskTemplateId = teacherFillTaskTemplateId;
	}

	@NotNull
	public Timestamp getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Timestamp startTime) {
		this.startTime = startTime;
	}

	@NotNull
	public Timestamp getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Timestamp endTime) {
		this.endTime = endTime;
	}

	@NotNull
	@Size(max = 64)
	public String getUsersId() {
		return this.usersId;
	}

	public void setUsersId(String usersId) {
		this.usersId = usersId;
	}

	@NotNull
	public Integer getTieId() {
		return this.tieId;
	}

	public void setTieId(Integer tieId) {
		this.tieId = tieId;
	}

	@NotNull
	public Byte getIsOk() {
		return this.isOk;
	}

	public void setIsOk(Byte isOk) {
		this.isOk = isOk;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("TeacherFillTaskInfo (");

		sb.append(id);
		sb.append(", ").append(title);
		sb.append(", ").append(createTime);
		sb.append(", ").append(teacherFillTaskTemplateId);
		sb.append(", ").append(startTime);
		sb.append(", ").append(endTime);
		sb.append(", ").append(usersId);
		sb.append(", ").append(tieId);
		sb.append(", ").append(isOk);

		sb.append(")");
		return sb.toString();
	}
}
