/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherFillTaskTemplate implements Serializable {

	private static final long serialVersionUID = 1600360762;

	private Integer   id;
	private String    title;
	private Timestamp createTime;
	private String    createUser;
	private Integer   tieId;
	private Integer   teachTaskInfoId;

	public TeacherFillTaskTemplate() {}

	public TeacherFillTaskTemplate(TeacherFillTaskTemplate value) {
		this.id = value.id;
		this.title = value.title;
		this.createTime = value.createTime;
		this.createUser = value.createUser;
		this.tieId = value.tieId;
		this.teachTaskInfoId = value.teachTaskInfoId;
	}

	public TeacherFillTaskTemplate(
		Integer   id,
		String    title,
		Timestamp createTime,
		String    createUser,
		Integer   tieId,
		Integer   teachTaskInfoId
	) {
		this.id = id;
		this.title = title;
		this.createTime = createTime;
		this.createUser = createUser;
		this.tieId = tieId;
		this.teachTaskInfoId = teachTaskInfoId;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@NotNull
	@Size(max = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@NotNull
	public Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	@NotNull
	@Size(max = 64)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@NotNull
	public Integer getTieId() {
		return this.tieId;
	}

	public void setTieId(Integer tieId) {
		this.tieId = tieId;
	}

	@NotNull
	public Integer getTeachTaskInfoId() {
		return this.teachTaskInfoId;
	}

	public void setTeachTaskInfoId(Integer teachTaskInfoId) {
		this.teachTaskInfoId = teachTaskInfoId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("TeacherFillTaskTemplate (");

		sb.append(id);
		sb.append(", ").append(title);
		sb.append(", ").append(createTime);
		sb.append(", ").append(createUser);
		sb.append(", ").append(tieId);
		sb.append(", ").append(teachTaskInfoId);

		sb.append(")");
		return sb.toString();
	}
}
