/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeachTaskInfo implements Serializable {

	private static final long serialVersionUID = -493314744;

	private Integer   id;
	private Integer   tieId;
	private String    teachTaskFileUrl;
	private String    teachTaskFileSize;
	private String    teachTaskFileName;
	private Timestamp teachTaskFileDate;
	private String    teachTaskTerm;
	private Integer   teachTaskDownTimes;
	private Integer   teachTypeId;
	private Date      termStartTime;
	private Date      termEndTime;
	private String    fileUser;
	private String    fileType;

	public TeachTaskInfo() {}

	public TeachTaskInfo(TeachTaskInfo value) {
		this.id = value.id;
		this.tieId = value.tieId;
		this.teachTaskFileUrl = value.teachTaskFileUrl;
		this.teachTaskFileSize = value.teachTaskFileSize;
		this.teachTaskFileName = value.teachTaskFileName;
		this.teachTaskFileDate = value.teachTaskFileDate;
		this.teachTaskTerm = value.teachTaskTerm;
		this.teachTaskDownTimes = value.teachTaskDownTimes;
		this.teachTypeId = value.teachTypeId;
		this.termStartTime = value.termStartTime;
		this.termEndTime = value.termEndTime;
		this.fileUser = value.fileUser;
		this.fileType = value.fileType;
	}

	public TeachTaskInfo(
		Integer   id,
		Integer   tieId,
		String    teachTaskFileUrl,
		String    teachTaskFileSize,
		String    teachTaskFileName,
		Timestamp teachTaskFileDate,
		String    teachTaskTerm,
		Integer   teachTaskDownTimes,
		Integer   teachTypeId,
		Date      termStartTime,
		Date      termEndTime,
		String    fileUser,
		String    fileType
	) {
		this.id = id;
		this.tieId = tieId;
		this.teachTaskFileUrl = teachTaskFileUrl;
		this.teachTaskFileSize = teachTaskFileSize;
		this.teachTaskFileName = teachTaskFileName;
		this.teachTaskFileDate = teachTaskFileDate;
		this.teachTaskTerm = teachTaskTerm;
		this.teachTaskDownTimes = teachTaskDownTimes;
		this.teachTypeId = teachTypeId;
		this.termStartTime = termStartTime;
		this.termEndTime = termEndTime;
		this.fileUser = fileUser;
		this.fileType = fileType;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@NotNull
	public Integer getTieId() {
		return this.tieId;
	}

	public void setTieId(Integer tieId) {
		this.tieId = tieId;
	}

	@NotNull
	@Size(max = 500)
	public String getTeachTaskFileUrl() {
		return this.teachTaskFileUrl;
	}

	public void setTeachTaskFileUrl(String teachTaskFileUrl) {
		this.teachTaskFileUrl = teachTaskFileUrl;
	}

	@Size(max = 50)
	public String getTeachTaskFileSize() {
		return this.teachTaskFileSize;
	}

	public void setTeachTaskFileSize(String teachTaskFileSize) {
		this.teachTaskFileSize = teachTaskFileSize;
	}

	@NotNull
	@Size(max = 30)
	public String getTeachTaskFileName() {
		return this.teachTaskFileName;
	}

	public void setTeachTaskFileName(String teachTaskFileName) {
		this.teachTaskFileName = teachTaskFileName;
	}

	@NotNull
	public Timestamp getTeachTaskFileDate() {
		return this.teachTaskFileDate;
	}

	public void setTeachTaskFileDate(Timestamp teachTaskFileDate) {
		this.teachTaskFileDate = teachTaskFileDate;
	}

	@NotNull
	@Size(max = 20)
	public String getTeachTaskTerm() {
		return this.teachTaskTerm;
	}

	public void setTeachTaskTerm(String teachTaskTerm) {
		this.teachTaskTerm = teachTaskTerm;
	}

	public Integer getTeachTaskDownTimes() {
		return this.teachTaskDownTimes;
	}

	public void setTeachTaskDownTimes(Integer teachTaskDownTimes) {
		this.teachTaskDownTimes = teachTaskDownTimes;
	}

	@NotNull
	public Integer getTeachTypeId() {
		return this.teachTypeId;
	}

	public void setTeachTypeId(Integer teachTypeId) {
		this.teachTypeId = teachTypeId;
	}

	@NotNull
	public Date getTermStartTime() {
		return this.termStartTime;
	}

	public void setTermStartTime(Date termStartTime) {
		this.termStartTime = termStartTime;
	}

	@NotNull
	public Date getTermEndTime() {
		return this.termEndTime;
	}

	public void setTermEndTime(Date termEndTime) {
		this.termEndTime = termEndTime;
	}

	@NotNull
	@Size(max = 64)
	public String getFileUser() {
		return this.fileUser;
	}

	public void setFileUser(String fileUser) {
		this.fileUser = fileUser;
	}

	@Size(max = 15)
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("TeachTaskInfo (");

		sb.append(id);
		sb.append(", ").append(tieId);
		sb.append(", ").append(teachTaskFileUrl);
		sb.append(", ").append(teachTaskFileSize);
		sb.append(", ").append(teachTaskFileName);
		sb.append(", ").append(teachTaskFileDate);
		sb.append(", ").append(teachTaskTerm);
		sb.append(", ").append(teachTaskDownTimes);
		sb.append(", ").append(teachTypeId);
		sb.append(", ").append(termStartTime);
		sb.append(", ").append(termEndTime);
		sb.append(", ").append(fileUser);
		sb.append(", ").append(fileType);

		sb.append(")");
		return sb.toString();
	}
}
