/**
 * This class is generated by jOOQ
 */
package com.school.cbis.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tie implements Serializable {

	private static final long serialVersionUID = 1855691962;

	private Integer id;
	private String  tieName;
	private String  tieAddress;
	private String  tiePhone;
	private Integer tiePrincipalArticleInfoId;
	private Integer tieIntroduceArticleInfoId;
	private Integer tieTrainingGoalArticleInfoId;
	private Integer tieTraitArticleInfoId;
	private Integer yardId;

	public Tie() {}

	public Tie(Tie value) {
		this.id = value.id;
		this.tieName = value.tieName;
		this.tieAddress = value.tieAddress;
		this.tiePhone = value.tiePhone;
		this.tiePrincipalArticleInfoId = value.tiePrincipalArticleInfoId;
		this.tieIntroduceArticleInfoId = value.tieIntroduceArticleInfoId;
		this.tieTrainingGoalArticleInfoId = value.tieTrainingGoalArticleInfoId;
		this.tieTraitArticleInfoId = value.tieTraitArticleInfoId;
		this.yardId = value.yardId;
	}

	public Tie(
		Integer id,
		String  tieName,
		String  tieAddress,
		String  tiePhone,
		Integer tiePrincipalArticleInfoId,
		Integer tieIntroduceArticleInfoId,
		Integer tieTrainingGoalArticleInfoId,
		Integer tieTraitArticleInfoId,
		Integer yardId
	) {
		this.id = id;
		this.tieName = tieName;
		this.tieAddress = tieAddress;
		this.tiePhone = tiePhone;
		this.tiePrincipalArticleInfoId = tiePrincipalArticleInfoId;
		this.tieIntroduceArticleInfoId = tieIntroduceArticleInfoId;
		this.tieTrainingGoalArticleInfoId = tieTrainingGoalArticleInfoId;
		this.tieTraitArticleInfoId = tieTraitArticleInfoId;
		this.yardId = yardId;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@NotNull
	@Size(max = 30)
	public String getTieName() {
		return this.tieName;
	}

	public void setTieName(String tieName) {
		this.tieName = tieName;
	}

	@Size(max = 200)
	public String getTieAddress() {
		return this.tieAddress;
	}

	public void setTieAddress(String tieAddress) {
		this.tieAddress = tieAddress;
	}

	@Size(max = 20)
	public String getTiePhone() {
		return this.tiePhone;
	}

	public void setTiePhone(String tiePhone) {
		this.tiePhone = tiePhone;
	}

	public Integer getTiePrincipalArticleInfoId() {
		return this.tiePrincipalArticleInfoId;
	}

	public void setTiePrincipalArticleInfoId(Integer tiePrincipalArticleInfoId) {
		this.tiePrincipalArticleInfoId = tiePrincipalArticleInfoId;
	}

	public Integer getTieIntroduceArticleInfoId() {
		return this.tieIntroduceArticleInfoId;
	}

	public void setTieIntroduceArticleInfoId(Integer tieIntroduceArticleInfoId) {
		this.tieIntroduceArticleInfoId = tieIntroduceArticleInfoId;
	}

	public Integer getTieTrainingGoalArticleInfoId() {
		return this.tieTrainingGoalArticleInfoId;
	}

	public void setTieTrainingGoalArticleInfoId(Integer tieTrainingGoalArticleInfoId) {
		this.tieTrainingGoalArticleInfoId = tieTrainingGoalArticleInfoId;
	}

	public Integer getTieTraitArticleInfoId() {
		return this.tieTraitArticleInfoId;
	}

	public void setTieTraitArticleInfoId(Integer tieTraitArticleInfoId) {
		this.tieTraitArticleInfoId = tieTraitArticleInfoId;
	}

	@NotNull
	public Integer getYardId() {
		return this.yardId;
	}

	public void setYardId(Integer yardId) {
		this.yardId = yardId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Tie (");

		sb.append(id);
		sb.append(", ").append(tieName);
		sb.append(", ").append(tieAddress);
		sb.append(", ").append(tiePhone);
		sb.append(", ").append(tiePrincipalArticleInfoId);
		sb.append(", ").append(tieIntroduceArticleInfoId);
		sb.append(", ").append(tieTrainingGoalArticleInfoId);
		sb.append(", ").append(tieTraitArticleInfoId);
		sb.append(", ").append(yardId);

		sb.append(")");
		return sb.toString();
	}
}
